"""The ``loremfile`` command line interface (docs/06 §10).

Commands are added by the milestone that implements them. Present so far:

* ``catalog validate`` — M1.6
* ``manifest check`` / ``manifest update`` — M1.6, for the parts that do not need
  generated bytes. Building entries from ``build/fixtures/`` needs the generators and
  validators, so it arrives with M3.

Every command exits non-zero on any failure and supports ``--json``, which prints one
object: ``{"command", "ok", "summary", "items", "errors"}``.
"""

from __future__ import annotations

import datetime as dt
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import click

from loremfile import __version__, config, validators
from loremfile import build as build_module
from loremfile.catalog import Catalog, CatalogError
from loremfile.infra import apply as apply_infra
from loremfile.infra import audit as audit_infra
from loremfile.infra import locks
from loremfile.infra import probe as probe_module
from loremfile.infra import purge as purge_module
from loremfile.infra import r2 as r2_module
from loremfile.infra import tokens as tokens_module
from loremfile.infra import upload as upload_module
from loremfile.infra import usage as usage_module
from loremfile.infra import verify_live as verify_live_module
from loremfile.infra.cloudflare_api import Client, CloudflareError, ZoneScopeError
from loremfile.manifest import (
    LOCKED_FIELDS,
    Manifest,
    ManifestError,
    build_entry,
    render_formats_json,
    render_sha256sums,
)

Item = dict[str, str]


def _restrict(entries: list[dict[str, Any]], only: tuple[str, ...]) -> list[dict[str, Any]]:
    """Narrow manifest entries to `--only`, refusing a path the manifest does not hold.

    Silently ignoring an unknown path is how a staged publish reports success over an
    empty selection: "verified 0 of the paths you named" and "verified them all" render
    the same in a summary line.
    """
    if not only:
        return entries
    wanted = set(only)
    unknown = wanted - {entry["path"] for entry in entries}
    if unknown:
        raise ValueError(f"--only names paths not in the manifest: {', '.join(sorted(unknown))}")
    return [entry for entry in entries if entry["path"] in wanted]


def _zone_client() -> Client:
    """A Cloudflare client that has confirmed which zone it is pointed at.

    The account holds unrelated production zones (docs/10 §3), and a purge is a write.
    """
    client = Client.from_env()
    client.verify_zone()
    return client


#: `infra audit` distinguishes its two failures, because they have different remedies
#: and must open and close independently (docs/11 §7.2). The one that matters is
#: `AUDIT_UNUSABLE`: an audit that could not run has learned **nothing** about drift, so
#: the caller must leave the drift issue exactly as it found it. Collapsing the two would
#: let a run that failed on a bad token close a genuine drift issue.
AUDIT_CLEAN = 0
AUDIT_DRIFT = 1
AUDIT_UNUSABLE = 2
AUDIT_OUTCOMES = {AUDIT_CLEAN: "clean", AUDIT_DRIFT: "drift", AUDIT_UNUSABLE: "unusable"}


class UploadUnavailable(RuntimeError):
    """A publish mode whose producer does not exist yet.

    Raised rather than reported as a success over an empty directory: "uploaded 0 site
    objects" and "there is no site" look identical in a log, and only one of them means
    the deploy did its job.
    """


def _emit(
    command: str,
    *,
    ok: bool,
    summary: dict[str, Any],
    items: list[Item],
    errors: list[str],
    as_json: bool,
    extra: dict[str, Any] | None = None,
) -> int:
    if as_json:
        click.echo(
            json.dumps(
                {
                    "command": command,
                    "ok": ok,
                    "summary": summary,
                    "items": items,
                    "errors": errors,
                    **(extra or {}),
                },
                indent=2,
                ensure_ascii=False,
            )
        )
    else:
        for error in errors:
            click.echo(f"error: {error}", err=True)
        parts = ", ".join(f"{key}={value}" for key, value in summary.items())
        click.echo(f"{command}: {'ok' if ok else 'FAILED'}{f' ({parts})' if parts else ''}")
    return 0 if ok else 1


@click.group()
@click.version_option(__version__, "-V", "--version", prog_name="loremfile")
def main() -> None:
    """Generators, validators and tooling for loremfile.dev."""


# --- catalog ---------------------------------------------------------------


@main.group()
def catalog() -> None:
    """Work with catalog/*.yaml."""


@catalog.command("validate")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def catalog_validate(as_json: bool) -> None:
    """Schema and cross-checks on catalog/*.yaml."""
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    try:
        loaded = Catalog.load()
    except (CatalogError, ValueError) as exc:
        errors.append(str(exc))
    else:
        fixtures = list(loaded.fixtures())
        summary = {
            "formats": len(loaded.formats),
            "fixtures": len(fixtures),
            "phase1": sum(1 for f in fixtures if f.phase == 1),
        }
        items = [{"path": f.path, "status": "ok", "detail": f.size_class} for f in fixtures]
    sys.exit(
        _emit(
            "catalog validate",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


# --- build and validate ----------------------------------------------------


def _selection_options(func: Callable[..., None]) -> Callable[..., None]:
    """The filters shared by `build` and `validate` (docs/06 §5)."""
    for option in reversed(
        [
            click.option("--only", multiple=True, metavar="PATH", help="Exact fixture paths."),
            click.option(
                "--format",
                "formats",
                multiple=True,
                metavar="FMT",
                help="Restrict to these formats.",
            ),
            click.option(
                "--group",
                type=click.Choice(["media", "data", "other"]),
                help="Restrict to a format group.",
            ),
            click.option("--phase", type=int, help="Restrict to a catalog phase."),
            click.option("--json", "as_json", is_flag=True, help="Print one JSON object."),
        ]
    ):
        func = option(func)
    return func


def _report_audit(catalog_obj: Catalog, results: list[build_module.Built], *, as_json: bool) -> int:
    """Compare regenerated hashes with the manifest and split expected drift from real.

    docs/06 §8: drift is a warning that opens a `determinism` issue, never a deploy
    blocker — published bytes are canonical. The split matters because four media
    fixtures are known not to reproduce off the CI reference fleet (docs/06 §4), and an
    audit that reports them every month alongside genuine regressions trains everyone to
    close the issue unread. Expected drift is reported and does not fail the run; real
    drift does.
    """
    committed = Manifest.load().by_path
    by_path = catalog_obj.by_path
    expected: list[Item] = []
    real: list[Item] = []
    for built in results:
        entry = committed.get(built.path)
        if entry is None or entry["sha256"] == built.sha256:
            continue
        detail = f"manifest {entry['sha256'][:12]} vs rebuilt {built.sha256[:12]}"
        fixture = by_path[built.path]
        if fixture.expected_drift:
            expected.append({"path": built.path, "status": "expected", "detail": detail})
        else:
            real.append({"path": built.path, "status": "drifted", "detail": detail})

    summary = {
        "regenerated": len(results),
        "drifted": len(real),
        "expected_drift": len(expected),
    }
    errors = [f"{item['path']}: {item['detail']}" for item in real]
    if expected and not as_json:
        click.echo(
            "\nExpected drift (docs/06 §4 — not reproducible off the reference fleet, "
            "not a regression):",
            err=True,
        )
        for item in expected:
            click.echo(f"  {item['path']}: {item['detail']}", err=True)
    return _emit(
        "build --audit",
        ok=not real,
        summary=summary,
        items=[*real, *expected],
        errors=errors,
        as_json=as_json,
    )


@main.command("build")
@click.option(
    "--audit",
    "audit",
    is_flag=True,
    help="Report drift against the manifest instead of writing fixtures (docs/06 §8).",
)
@click.option(
    "--new",
    "selection",
    flag_value="new",
    help="Only fixtures absent from the merge-base manifest.",
)
@click.option(
    "--missing-in-bucket",
    "selection",
    flag_value="missing-in-bucket",
    help="Only fixtures absent from the bucket (M4.3).",
)
@click.option("--all", "selection", flag_value="all", default=True, help="Every active fixture.")
@_selection_options
def build_command(
    audit: bool,
    selection: str,
    only: tuple[str, ...],
    formats: tuple[str, ...],
    group: str | None,
    phase: int | None,
    as_json: bool,
) -> None:
    """Generate fixtures into build/fixtures/."""
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        catalog_obj = Catalog.load()

        def in_bucket() -> set[str]:
            """Called only when `--missing-in-bucket` is the selection."""
            return r2_module.list_keys(r2_module.client(), r2_module.bucket_name())

        chosen = build_module.select(
            catalog_obj,
            selection=build_module.Selection(selection),
            only=only,
            formats=formats,
            group=group,
            phase=phase,
            in_bucket=in_bucket,
        )
        results = build_module.build(chosen)
        if audit:
            sys.exit(_report_audit(catalog_obj, results, as_json=as_json))
        build_module.write_receipt(
            chosen,
            selection=selection,
            filters={
                "only": list(only),
                "formats": list(formats),
                "group": group,
                "phase": phase,
            },
        )
        summary = {"generated": len(results), "bytes": sum(len(r.data) for r in results)}
        items = [
            {"path": r.path, "status": "ok", "detail": f"{len(r.data)} bytes"} for r in results
        ]
    except (
        build_module.BuildError,
        CatalogError,
        r2_module.R2Error,
        ValueError,
        KeyError,
    ) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit("build", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json)
    )


@main.command("validate")
@_selection_options
def validate_command(
    only: tuple[str, ...],
    formats: tuple[str, ...],
    group: str | None,
    phase: int | None,
    as_json: bool,
) -> None:
    """Run the validators over build/fixtures/."""
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        catalog_obj = Catalog.load()
        build_module.load_generators()
        validators.load()
        chosen = build_module.select(
            catalog_obj, only=only, formats=formats, group=group, phase=phase
        )
        directory = build_module.fixtures_dir()
        # Validate what the preceding build produced, not everything in the catalog.
        # `build --new` generates only the fixtures a pull request adds, and the bare
        # `loremfile validate` that follows it in ci.yml has to mean "check those".
        # Only paths named explicitly with --only are required to be present; anything
        # else simply was not part of this build.
        explicit = set(only)
        present = [f for f in chosen if (directory / f.path).is_file()]
        for path in sorted(explicit - {f.path for f in present}):
            errors.append(f"{path}: not generated; run `loremfile build --only {path}` first")
            items.append({"path": path, "status": "missing", "detail": ""})

        # The receipt says what the last build set out to generate. Anything it selected
        # that is not on disk is a build that half-failed, whatever its exit code said.
        receipt = build_module.read_receipt()
        expected = (
            {p for p in receipt.selected if p in {f.path for f in chosen}} if receipt else set()
        )
        for path in sorted(expected - {f.path for f in present}):
            errors.append(f"{path}: selected by the last build but never written")
            items.append({"path": path, "status": "missing", "detail": ""})

        if not present and not errors and receipt is None:
            # No receipt means no build ran here. An empty directory with a receipt is a
            # build that correctly selected nothing — the shape of a pull request that
            # changes no catalog entry — and reporting that as a failure would make
            # ci.yml red on every infrastructure-only change.
            errors.append(
                "nothing to validate: build/fixtures is empty. Run `loremfile build` first."
            )
        passed = 0
        for fixture in present:
            target = directory / fixture.path
            report = validators.validate(
                target.read_bytes(), fixture, catalog_obj.mime_for(fixture)
            )
            if report.ok:
                passed += 1
                items.append({"path": fixture.path, "status": "ok", "detail": ""})
            else:
                errors += [f"{fixture.path}: {failure}" for failure in report.failures]
                items.append(
                    {"path": fixture.path, "status": "failed", "detail": "; ".join(report.failures)}
                )
        summary = {
            "validated": passed,
            "failed": len(present) - passed,
            "skipped_not_built": len(chosen) - len(present),
            "selected_by_last_build": len(receipt.selected) if receipt else "no build receipt",
        }
    except (build_module.BuildError, CatalogError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "validate", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json
        )
    )


# --- infra -----------------------------------------------------------------


@main.group()
def infra() -> None:
    """Desired-state files for Cloudflare and R2 (docs/08)."""


@infra.command("apply")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Resolve and print the plan, including the target zone, without writing.",
)
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def infra_apply(dry_run: bool, as_json: bool) -> None:
    """Apply infra/ to Cloudflare (docs/08 §6). Runs from infra.yml, never locally.

    The zone is verified against its hostname before anything writes, and the plan names
    the zone it resolved: ruleset entry points are written with a full PUT, and this
    account holds unrelated production zones.
    """
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        client = Client.from_env(dry_run=dry_run)
        report = apply_infra.run(client)
        click.echo(report.render(), err=True)
        items = [
            {"path": o.resource, "status": o.state, "detail": o.detail} for o in report.outcomes
        ]
        summary = {
            "zone": report.hostname,
            "zone_id": report.zone_id,
            "dry_run": dry_run,
            **{
                state: sum(1 for o in report.outcomes if o.state == state)
                for state in ("unchanged", "updated", "skipped", "manual", "failed")
            },
        }
        errors = [f"{o.resource}: {o.detail}" for o in report.outcomes if o.state == "failed"]
    except ZoneScopeError as exc:
        # Never folded into the generic handler: this is the guard that protects the
        # other zones on the account, and it must read as its own kind of failure.
        errors.append(f"ZONE SCOPE REFUSED — nothing was written: {exc}")
    except CloudflareError as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "infra apply",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


@main.command("upload")
@click.option("--fixtures", "fixtures", is_flag=True, help="Publish missing manifest entries.")
@click.option(
    "--apply-removals",
    "removals",
    is_flag=True,
    help="Delete objects whose manifest entry is status: removed (takedown flow).",
)
@click.option("--site", "site", is_flag=True, help="Publish build/site/ (M4.1).")
@click.option(
    "--carry-forward",
    "carry_forward",
    type=click.Path(path_type=Path, file_okay=False),
    help="Directory holding the bytes of expected_drift fixtures (the CI artifact).",
)
@click.option(
    "--only",
    "only",
    multiple=True,
    metavar="PATH",
    help="Publish only these manifest paths (staged first publish).",
)
@click.option("--dry-run", "dry_run", is_flag=True, help="Print the plan; write nothing.")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def upload_command(
    fixtures: bool,
    removals: bool,
    site: bool,
    carry_forward: Path | None,
    only: tuple[str, ...],
    dry_run: bool,
    as_json: bool,
) -> None:
    """Publish to R2 (docs/09 §5). Needs T2; never overwrites a fixture."""
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    chosen = [
        name
        for name, on in (("--fixtures", fixtures), ("--apply-removals", removals), ("--site", site))
        if on
    ]
    if len(chosen) != 1:
        sys.exit(
            _emit(
                "upload",
                ok=False,
                summary={},
                items=[],
                errors=["choose exactly one of --fixtures, --apply-removals, --site"],
                as_json=as_json,
            )
        )
    try:
        if site:
            raise UploadUnavailable(
                "--site needs `loremfile site build`, which arrives with M4.1. Publishing "
                "an empty build/site/ would report success for a site that does not "
                "exist. `--force-site` arrives with it, for the same reason: an option "
                "that changes nothing is worse than an absent one."
            )
        manifest = Manifest.load()
        bucket = r2_module.bucket_name()
        s3 = r2_module.client()
        if fixtures:
            # `--only` narrows the *plan*, so the gates still run over exactly the keys
            # that are about to be written and no others: a staged publish gets the same
            # lock and carry-forward checks as a full one, not a weaker pass.
            entries = _restrict(list(manifest.active), only)
            live = r2_module.live_hashes(s3, bucket, [e["path"] for e in entries])
            catalog_obj = Catalog.load()
            available = upload_module.sources(
                [e["path"] for e in entries],
                catalog=catalog_obj,
                build_dir=build_module.fixtures_dir(),
                carry_forward=carry_forward,
            )
            plan = upload_module.plan_fixtures(
                entries,
                live,
                available,
                catalog=catalog_obj,
                lock_rules=locks.committed_rules(),
            )
            # Hash what is about to be published. The carry-forward bytes come from a
            # different workflow run, so they are untrusted input; this is what makes
            # downloading that artifact loosely safe.
            plan.blockers += upload_module.verify_sources(plan, entries)
        else:
            # Only the tombstones. HEADing every published fixture to find out which of
            # them is being removed would be ~160 Class B reads to answer a question the
            # manifest already answers.
            tombstoned = [
                e["path"] for e in _restrict(manifest.entries, only) if e.get("status") == "removed"
            ]
            live = r2_module.live_hashes(s3, bucket, tombstoned)
            plan = upload_module.plan_removals(manifest.entries, live)

        click.echo(plan.render(), err=True)
        by_path = manifest.by_path
        done = 0
        if plan.ok and not dry_run:
            for step in plan.steps:
                if step.action is upload_module.Action.UPLOAD:
                    entry = by_path[step.key]
                    r2_module.put_fixture(
                        s3,
                        bucket,
                        step.key,
                        Path(step.source),
                        mime=str(entry["mime"]),
                        sha256=str(entry["sha256"]),
                    )
                    done += 1
                elif step.action is upload_module.Action.REMOVE:
                    r2_module.delete(s3, bucket, step.key)
                    # docs/09 §5: delete *and* purge. A removed object still cached at
                    # the edge is still being served, which is the only thing a takedown
                    # is measured on.
                    purged = purge_module.purge_removed_url(
                        _zone_client(), f"https://{config.SITE_HOST}/{step.key}"
                    )
                    errors += purged.errors
                    done += 1
        summary = {
            "mode": chosen[0].lstrip("-"),
            "uploaded": len(plan.by_action(upload_module.Action.UPLOAD)),
            "skipped": len(plan.by_action(upload_module.Action.SKIP)),
            "removed": len(plan.by_action(upload_module.Action.REMOVE)),
            "failed": len(plan.by_action(upload_module.Action.FAIL)),
            "bytes": sum(s.size for s in plan.by_action(upload_module.Action.UPLOAD)),
            "written": done,
            "dry_run": dry_run,
            "only": len(only),
        }
        items = [
            {"path": step.key, "status": step.action.value, "detail": step.reason}
            for step in plan.steps
            if step.action is not upload_module.Action.SKIP
        ]
        errors = [
            *plan.blockers,
            *(f"{s.key}: {s.reason}" for s in plan.by_action(upload_module.Action.FAIL)),
        ]
    except ZoneScopeError as exc:
        errors.append(f"ZONE SCOPE REFUSED: {exc}")
    except (
        UploadUnavailable,
        r2_module.R2Error,
        CloudflareError,
        ManifestError,
        CatalogError,
        OSError,
        ValueError,
    ) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit("upload", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json)
    )


@main.command("purge")
@click.option("--site", "site", is_flag=True, help="Purge the site keys and format pages.")
@click.option("--url", "url", help="Purge one URL (takedown only, docs/11 §7.8).")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def purge_command(site: bool, url: str | None, as_json: bool) -> None:
    """Purge cached site content (docs/09 §6).

    Fixtures are never purged by `--site`: their bytes never change, so a purge could
    only discard a still-correct entry and cost an R2 read to refetch identical bytes.
    `--url` is the takedown path and names the URL explicitly.
    """
    errors: list[str] = []
    summary: dict[str, Any] = {}
    try:
        client = Client.from_env()
        client.verify_zone()
        if url:
            report = purge_module.purge_removed_url(client, url)
        elif site:
            formats = sorted({f.format for f in Catalog.load().fixtures()})
            prefixes, files = purge_module.site_targets(formats)
            report = purge_module.purge(client, prefixes, files)
        else:
            raise ValueError("choose --site or --url")
        click.echo(report.render(), err=True)
        summary = {"batches": report.batches, "prefixes": report.prefixes, "files": report.files}
        errors = report.errors
    except ZoneScopeError as exc:
        errors.append(f"ZONE SCOPE REFUSED — nothing was purged: {exc}")
    except (CloudflareError, CatalogError, ValueError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit("purge", ok=not errors, summary=summary, items=[], errors=errors, as_json=as_json)
    )


@main.command("verify-live")
@click.option(
    "--mode",
    type=click.Choice(["smoke", "daily", "full"]),
    default="smoke",
    help="How much of the catalog to check (docs/12 §4).",
)
@click.option(
    "--inject-failure",
    metavar="PATH",
    help="Report PATH as failing without it being so, to exercise the issue automation.",
)
@click.option(
    "--only",
    "only",
    multiple=True,
    metavar="PATH",
    help="Check only these manifest paths, whatever --mode says.",
)
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def verify_live_command(
    mode: str, inject_failure: str | None, only: tuple[str, ...], as_json: bool
) -> None:
    """Check production against the manifest (docs/12 §4). Needs no credentials."""
    errors: list[str] = []
    report = verify_live_module.LiveReport()
    try:
        manifest = Manifest.load()
        entries = list(manifest.active)
        if only:
            # An explicit list beats the mode's sampling: the point of naming paths is to
            # check those paths, and `smoke` would otherwise silently drop most of them.
            chosen = _restrict(entries, only)
        else:
            chosen = verify_live_module.smallest_per_format(entries) if mode == "smoke" else entries
        for entry in chosen:
            response = verify_live_module.fetch(f"/{entry['path']}")
            report.findings += verify_live_module.check_fixture_headers(entry, response)
            small = entry["bytes"] < verify_live_module.DAILY_HASH_LIMIT_BYTES
            hash_it = mode == "full" or (mode == "daily" and small)
            if hash_it:
                body = verify_live_module.fetch(f"/{entry['path']}", method="GET")
                report.findings.append(verify_live_module.check_fixture_bytes(entry, body))
        if inject_failure:
            # REQ-27: the issue automation is a control, and a control nobody has seen
            # fire is one nobody can trust. This makes it fire on demand.
            report.add(
                inject_failure,
                verify_live_module.Status.HASH_MISMATCH,
                "injected by --inject-failure; not a real mismatch",
            )
        click.echo(report.render(), err=True)
        errors = [f"{f.path}: {f.status.value} {f.detail}".strip() for f in report.failures()]
    except (ManifestError, OSError, ValueError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "verify-live",
            ok=not errors,
            summary={
                "mode": "only" if only else mode,
                "checked": len(report.findings),
                "failing": len(errors),
            },
            items=[
                {"path": f.path, "status": f.status.value, "detail": f.detail}
                for f in report.findings
            ],
            errors=errors,
            as_json=as_json,
        )
    )


@main.command("tokens-due")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def tokens_due_command(as_json: bool) -> None:
    """Tokens expiring within the rotation warning window (docs/08 §6).

    Reads dates only from `infra/token-expiry.json`; the file never holds a secret. The
    value here is lead time — a token that expires without warning takes the deploy with
    it, and rotation is an owner action that cannot be done at short notice.
    """
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        rows = tokens_module.tokens_due()
        items = [
            {
                "path": row.name,
                "status": "due" if row.due else "ok",
                "detail": f"expires {row.expires.isoformat()} ({row.days_left} days)",
            }
            for row in rows
        ]
        due = [row for row in rows if row.due]
        summary = {"tokens": len(rows), "due": len(due)}
        errors = [
            f"{row.name}: expires {row.expires.isoformat()} in {row.days_left} days" for row in due
        ]
        for row in rows:
            click.echo(
                f"  {row.name:24s} {row.expires.isoformat()}  {row.days_left:>4d} days"
                f"{'  <-- rotate' if row.due else ''}",
                err=True,
            )
    except (OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    # `due` is a count, not a failure: health.yml decides the state from the summary, so
    # the command exits 0 with the number and lets the caller apply the threshold.
    sys.exit(
        _emit("tokens-due", ok=True, summary=summary, items=items, errors=errors, as_json=as_json)
    )


@main.command("usage")
@click.option("--days", type=int, default=0, help="Look back N days instead of month-to-date.")
@click.option(
    "--daily-days",
    type=int,
    default=usage_module.MAX_WINDOW_DAYS,
    help="Days of per-day history to include; 0 omits the series.",
)
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def usage_command(days: int, daily_days: int, as_json: bool) -> None:
    """R2 operations from the Analytics API (docs/19 §3). Read-only, T4."""
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    series: list[dict[str, Any]] = []
    try:
        if days:
            now = dt.datetime.now(tz=dt.UTC)
            counts = usage_module.operations(now - dt.timedelta(days=days), now)
        else:
            counts = usage_module.month_to_date()
        click.echo(counts.render(), err=True)
        # docs/09 §4's health.yml step reads `summary.r2_class_b_mtd`, so the key names
        # the metric exactly. A windowed run gets a different key rather than claiming
        # to be month-to-date, because a threshold compared against the wrong window is
        # the kind of wrong that looks right.
        suffix = "window" if days else "mtd"
        summary = {
            f"r2_class_a_{suffix}": counts.class_a,
            f"r2_class_b_{suffix}": counts.class_b,
            "missing_key_reads": counts.missing_key_reads,
            "days": days or "month-to-date",
        }
        items = [
            {
                "path": f"{row['dimensions']['actionType']}/{row['dimensions']['actionStatus']}",
                "status": "counted",
                "detail": str(row["sum"]["requests"]),
            }
            for row in counts.rows
        ]
    except usage_module.UsageError as exc:
        errors.append(str(exc))
    # The daily series is fetched separately and its failure is reported separately: a
    # month-to-date read that worked must not be discarded because the series did not,
    # and a series that silently vanished must not read as a quiet period.
    if daily_days:
        try:
            series = [day.as_dict() for day in usage_module.recent_days(daily_days)]
        except usage_module.UsageError as exc:
            errors.append(f"daily series: {exc}")
    sys.exit(
        _emit(
            "usage",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
            extra={"daily": series},
        )
    )


@infra.command("audit")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def infra_audit(as_json: bool) -> None:
    """Report how the zone differs from infra/ (docs/09 §3.4). Reads; never writes.

    Not `apply --dry-run`. A dry run rehearses the write and reports what it *would*
    do — and because ruleset phases are written with an unconditional PUT, that is
    `updated` on every run whether or not anything differs. This reads the deployed
    state and compares content, so `drift` means drift.
    """
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    code = AUDIT_CLEAN
    try:
        # Read-only at the transport: a check that grew a write raises rather than
        # quietly converging the drift it was sent to report.
        client = Client.from_env(read_only=True)
        report = audit_infra.run(client)
        click.echo(report.render(), err=True)
        summary = {
            "zone": report.hostname,
            "zone_id": report.zone_id,
            "checked": len(report.findings),
            "drift": len(report.drifted),
            "unreadable": len(report.unreadable),
        }
        items = [
            {"path": f.resource, "status": f.state, "detail": f.detail} for f in report.findings
        ]
        errors = [f"{f.resource}: {f.detail}" for f in report.drifted]
        code = AUDIT_DRIFT if report.drifted else AUDIT_CLEAN
    except ZoneScopeError as exc:
        errors.append(f"ZONE SCOPE REFUSED: {exc}")
        code = AUDIT_UNUSABLE
    except (CloudflareError, OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
        code = AUDIT_UNUSABLE
    _emit(
        "infra audit",
        ok=code == AUDIT_CLEAN,
        summary={**summary, "outcome": AUDIT_OUTCOMES[code]},
        items=items,
        errors=errors,
        as_json=as_json,
    )
    sys.exit(code)


@infra.command("locks")
@click.option("--write", is_flag=True, help="Rewrite infra/r2-locks.json.")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def infra_locks(write: bool, as_json: bool) -> None:
    """Generate or check the R2 bucket lock rules (docs/08 §7b).

    One rule per format prefix. A format added without its rule is a prefix a leaked T2
    could overwrite, so this is generated from the catalog rather than maintained by hand.
    """
    errors: list[str] = []
    summary: dict[str, Any] = {}
    try:
        catalog_obj = Catalog.load()
        rules = locks.desired_rules(catalog_obj)
        if write:
            locks.locks_path().write_text(locks.render(catalog_obj), encoding="utf-8")
        else:
            errors = locks.diff(catalog_obj)
        summary = {"rules": len(rules), "written": write}
    except (CatalogError, OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "infra locks", ok=not errors, summary=summary, items=[], errors=errors, as_json=as_json
        )
    )


@main.command("probe")
@click.option("--up", "up", is_flag=True, help="Upload the objects the checks read.")
@click.option("--down", "down", is_flag=True, help="Delete everything under _probe/.")
@click.option("--skip-rate-limit", is_flag=True, help="Everything except the 400-request burst.")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def probe_command(up: bool, down: bool, skip_rate_limit: bool, as_json: bool) -> None:
    """Behavioural checks against production (docs/15 M2.4).

    Writes only under `_probe/` and `_locktest/`, neither of which is a fixture path
    (docs/03 §7.1). A check whose precondition is unmet **fails**: "the header is absent"
    and "there was nothing to put a header on" are different results, and only one of
    them is information.
    """
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        if up:
            written = probe_module.upload_probe_objects()
            summary = {"uploaded": len(written)}
            items = [{"path": key, "status": "uploaded", "detail": ""} for key in written]
        elif down:
            removed = probe_module.delete_probe_objects()
            summary = {"deleted": len(removed)}
            items = [{"path": key, "status": "deleted", "detail": ""} for key in removed]
        else:
            checks = {**probe_module.SITE_CHECKS, **probe_module.BUCKET_CHECKS}
            if skip_rate_limit:
                checks.pop("rate-limit", None)
            report = probe_module.run_checks(checks)
            click.echo(report.render(), err=True)
            items = [
                {"path": r.name, "status": r.state, "detail": r.detail} for r in report.results
            ]
            errors = [f"{r.name}: {r.detail}" for r in report.results if r.state == "fail"]
            summary = {
                "checks": len(report.results),
                "failed": sum(1 for r in report.results if r.state == "fail"),
            }
    except (probe_module.CheckFailed, OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit("probe", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json)
    )


# --- manifest --------------------------------------------------------------


@main.group()
def manifest() -> None:
    """Work with manifest.json, sha256sums.txt and formats.json."""


def _names_a_path(message: str, paths: set[str]) -> bool:
    """Does this diagnostic concern one of `paths`? Lock diffs lead with `<path>: `.

    Matched exactly, never by prefix. The set is five enumerable paths, so a prefix
    match would be broader than the evidence supports and would invite marking `opus/`
    wholesale later — which would silently exempt every future Opus fixture from the
    strongest check the project has.
    """
    head, separator, _ = message.partition(": ")
    return bool(separator) and head in paths


def _check_manifest_against_catalog() -> tuple[Manifest, list[str]]:
    """Rules that need no generated bytes: removals, totals, internal consistency."""
    loaded = Manifest.load()
    errors: list[str] = []
    try:
        catalog_obj = Catalog.load()
    except (CatalogError, ValueError) as exc:
        return loaded, [str(exc)]

    catalog_paths = {f.path for f in catalog_obj.fixtures()}
    removable = {f.path: f.removed for f in catalog_obj.fixtures() if f.removed is not None}
    errors += loaded.check_removals(catalog_paths, removable)
    errors += loaded.check_total_bytes()
    return loaded, errors


def _entries_from_build(
    catalog_obj: Catalog, committed: Manifest
) -> tuple[list[dict[str, Any]], list[str]]:
    """Build manifest entries from whatever is in build/fixtures/.

    Only fixtures that were actually generated are considered, so `manifest update`
    after a partial build adds only what that build produced. Every entry is validated
    first: an entry never reaches the manifest without its props being measured.
    """
    build_module.load_generators()
    validators.load()
    directory = build_module.fixtures_dir()
    entries: list[dict[str, Any]] = []
    errors: list[str] = []
    existing = committed.by_path

    for fixture in catalog_obj.fixtures():
        target = directory / fixture.path
        if not target.is_file() or fixture.awaiting_publication:
            continue
        data = target.read_bytes()
        mime = catalog_obj.mime_for(fixture)
        report = validators.validate(data, fixture, mime)
        if not report.ok:
            errors += [f"{fixture.path}: {failure}" for failure in report.failures]
            continue
        entry = build_entry(
            fixture,
            data,
            report.props,
            mime,
            added_in=existing.get(fixture.path, {}).get("added_in", config.CATALOG_VERSION),
        )
        entries.append(entry)

    # The lock rule is the point of the whole exercise: refuse before writing.
    diffs = committed.check_lock({e["path"]: e for e in entries})
    errors += [str(diff) for diff in diffs]
    return entries, errors


@manifest.command("check")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_check(as_json: bool) -> None:
    """Verify the committed manifest, including against whatever the build produced.

    docs/06 §7: for every fixture generated in this run, the committed `sha256`, `bytes`
    and `mime` must equal the regenerated values. That half was deferred to M3 and is
    implemented here, in M3.6 — the first milestone where an author's machine and CI
    actually disagreed, because libx264, libvpx and libopus each dispatch on the CPU
    features they find and no ffmpeg flag reaches that choice.

    When they disagree, docs/11 §5 promises the exact entries to commit rather than a
    pair of truncated hashes, so the author can take CI's answer without guessing.
    """
    loaded, errors = _check_manifest_against_catalog()
    items: list[Item] = []
    corrections: list[dict[str, Any]] = []
    regenerated: list[dict[str, Any]] = []
    if not errors:
        catalog_for_check = Catalog.load()
        try:
            regenerated, lock_errors = _entries_from_build(catalog_for_check, loaded)
        except (build_module.BuildError, CatalogError, ValueError, KeyError) as exc:
            lock_errors = [str(exc)]
        # A path marked `expected_drift` is known not to reproduce byte for byte, so a
        # mismatch on it is reported and does not fail. M3.6 measured why: two attempts
        # of the *same* commit on the *same* runner label produced different bytes for
        # opus/30s.opus and webm/720p-5s-vp9.webm, and a check that cannot pass twice in
        # a row is a check that gets disabled. Everything else stays fatal.
        drift_expected = {f.path for f in catalog_for_check.fixtures() if f.expected_drift}
        # Published on the base branch already, so its bytes are in the bucket and a
        # rebuild that drifts says nothing. New here, and they exist only in this run.
        published_before = set(build_module.merge_base_manifest().by_path)
        errors += [e for e in lock_errors if not _names_a_path(e, drift_expected)]
        committed = loaded.by_path
        for entry in regenerated:
            old = committed.get(entry["path"])
            if old is None:
                continue
            differing = [f for f in LOCKED_FIELDS if old.get(f) != entry.get(f)]
            if not differing:
                continue
            if entry["path"] in drift_expected:
                if entry["path"] not in published_before:
                    # The guard this milestone was missing. A path whose bytes cannot be
                    # rebuilt may only enter the manifest in a run that produced those
                    # exact bytes — that run's carry-forward artifact is then the only
                    # copy, and it matches. Entering on a run that drifted is how five
                    # entries came to describe bytes that existed nowhere.
                    errors.append(
                        f"{entry['path']}: new in this branch, marked expected_drift, and "
                        "the bytes this run built do not match the committed entry. Its "
                        "bytes cannot be rebuilt later, so commit the entry this run "
                        "produced (`manifest adopt`) or withhold it with "
                        "awaiting_publication (docs/03 §7.1)."
                    )
                    items.append(
                        {"path": entry["path"], "status": "unfulfillable", "detail": "no bytes"}
                    )
                    corrections.append(entry)
                    continue
                items.append(
                    {
                        "path": entry["path"],
                        "status": "expected-drift",
                        "detail": ",".join(differing),
                    }
                )
                # Still printed, though it does not fail: until the deploy publishes
                # them these entries are adoptable, and the manifest has to describe the
                # same bytes as the carry-forward artifact from this very run.
                corrections.append(entry)
                continue
            corrections.append(entry)
            items.append(
                {"path": entry["path"], "status": "differs", "detail": ",".join(differing)}
            )
        errors += [
            w
            for w in loaded.props_warnings({e["path"]: e for e in regenerated})
            if not _names_a_path(w, drift_expected)
        ]
        expected_seen = [i for i in items if i["status"] == "expected-drift"]
        if expected_seen and not as_json:
            click.echo(
                "\nExpected drift, not a failure (docs/06 §4 — these do not reproduce "
                "byte for byte between runs):",
                err=True,
            )
            for item in expected_seen:
                click.echo(f"  {item['path']}: {item['detail']}", err=True)

    active = loaded.active
    summary = {
        "entries": len(loaded.entries),
        "active": len(active),
        "tombstones": len(loaded.entries) - len(active),
        "total_bytes": sum(e["bytes"] for e in active),
        "regenerated": len(regenerated),
    }
    if corrections and not as_json:
        click.echo(
            "\nThe bytes this machine produced differ from the committed manifest. "
            "Encoder libraries dispatch on CPU features, so an author's machine and CI "
            "can disagree; CI is the authority (docs/06 §4). Commit these entries:\n",
            err=True,
        )
        click.echo(json.dumps(corrections, indent=2, ensure_ascii=False, sort_keys=True))
    sys.exit(
        _emit(
            "manifest check",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


@manifest.command("adopt")
@click.option(
    "--from",
    "source",
    required=True,
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="JSON array of entries, as `manifest check` prints them.",
)
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_adopt(source: Path, as_json: bool) -> None:
    """Take CI's entries for fixtures this machine cannot reproduce (docs/06 §4).

    libx264, libvpx and libopus dispatch on the CPU features they find, so an author's
    machine and CI can produce different bytes for the same fixture and no ffmpeg flag
    reaches that choice. CI is the authority, because CI is what builds the bytes the
    deploy uploads — so its entries have to be committable without hand-editing the
    manifest, which AGENTS.md forbids for good reason.

    The refusal that matters is the last one: a fixture already published on the base
    branch may never change its bytes, whatever any machine now produces. Adopting is
    only ever allowed for paths this branch is adding.
    """
    errors: list[str] = []
    items: list[Item] = []
    adopted: list[dict[str, Any]] = []
    try:
        incoming = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(incoming, list):
            raise ValueError("expected a JSON array of manifest entries")
        loaded = Manifest.load()
        catalog_obj = Catalog.load()
        mime_defaults = {fmt.format: fmt.mime for fmt in catalog_obj.formats}
        known = catalog_obj.by_path
        published = build_module.merge_base_manifest().by_path

        for entry in incoming:
            path = entry.get("path")
            if path not in known:
                errors.append(f"{path}: not in the catalog")
                continue
            missing = [f for f in (*LOCKED_FIELDS, "path", "props") if f not in entry]
            if missing:
                errors.append(f"{path}: entry is missing {missing}")
                continue
            was = published.get(path)
            if was is not None:
                frozen = [f for f in LOCKED_FIELDS if was.get(f) != entry.get(f)]
                if frozen:
                    errors.append(
                        f"{path}: already published on the base branch and {frozen} would "
                        "change. Published bytes are frozen forever (docs/01 REQ-2): "
                        "publish a new path with supersededBy instead."
                    )
                    continue
            adopted.append(entry)
            items.append({"path": path, "status": "adopted", "detail": entry["sha256"][:12]})

        if not errors:
            by_path = loaded.by_path
            changed = any(by_path.get(e["path"]) != e for e in adopted)
            for entry in adopted:
                by_path[entry["path"]] = entry
            loaded.entries = sorted(by_path.values(), key=lambda e: e["path"])
            loaded.touch(changed=changed)
            loaded.save()
            config.sha256sums_path().write_text(
                render_sha256sums(loaded), encoding="utf-8", newline="\n"
            )
            config.formats_json_path().write_text(
                render_formats_json(loaded, mime_defaults), encoding="utf-8", newline="\n"
            )
    except (ManifestError, CatalogError, OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "manifest adopt",
            ok=not errors,
            summary={"adopted": len(adopted) if not errors else 0},
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


@manifest.command("update")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_update(as_json: bool) -> None:
    """Rewrite manifest.json, sha256sums.txt and formats.json.

    Never hand-edit those files: run this inside the toolchain container and commit
    exactly what it writes (AGENTS.md).
    """
    loaded, errors = _check_manifest_against_catalog()
    if errors:
        sys.exit(
            _emit("manifest update", ok=False, summary={}, items=[], errors=errors, as_json=as_json)
        )
    try:
        catalog_obj = Catalog.load()
        mime_defaults = {fmt.format: fmt.mime for fmt in catalog_obj.formats}
        added, lock_errors = _entries_from_build(catalog_obj, loaded)
        if lock_errors:
            sys.exit(
                _emit(
                    "manifest update",
                    ok=False,
                    summary={},
                    items=[],
                    errors=lock_errors,
                    as_json=as_json,
                )
            )
        by_path = loaded.by_path
        # docs/03 §7.1, amended in M3.6: immutability attaches on publication to R2, not
        # on entry into the manifest. A fixture marked `awaiting_publication` therefore
        # leaves the manifest outright rather than becoming a tombstone, which would
        # assert a publication that never happened. The guard is that it may never have
        # been published: anything present on the base branch stays, and says so.
        published = build_module.merge_base_manifest().by_path
        withdrawn: list[str] = []
        for fixture in catalog_obj.fixtures():
            if not fixture.awaiting_publication or fixture.path not in by_path:
                continue
            if fixture.path in published:
                sys.exit(
                    _emit(
                        "manifest update",
                        ok=False,
                        summary={},
                        items=[],
                        errors=[
                            f"{fixture.path}: awaiting_publication, but it is already in "
                            "the base branch manifest. Withdrawing a published path is "
                            "forbidden (docs/03 §7.1); use a tombstone or supersede it."
                        ],
                        as_json=as_json,
                    )
                )
            del by_path[fixture.path]
            withdrawn.append(fixture.path)

        # docs/06 §7 step 5: generated_at moves only when something actually changed,
        # so an unchanged rebuild produces no diff at all. Comparing the assembled
        # entries — not merely "did we build anything" — is what makes that true.
        changed = bool(withdrawn) or any(by_path.get(entry["path"]) != entry for entry in added)
        for entry in added:
            by_path[entry["path"]] = entry
        loaded.entries = sorted(by_path.values(), key=lambda e: e["path"])
        changed = changed or loaded.catalog_version != config.CATALOG_VERSION
        loaded.catalog_version = config.CATALOG_VERSION
        loaded.touch(changed=changed)
        loaded.save()
        config.sha256sums_path().write_text(
            render_sha256sums(loaded), encoding="utf-8", newline="\n"
        )
        config.formats_json_path().write_text(
            render_formats_json(loaded, mime_defaults), encoding="utf-8", newline="\n"
        )
    except (ManifestError, CatalogError, OSError) as exc:
        sys.exit(
            _emit(
                "manifest update",
                ok=False,
                summary={},
                items=[],
                errors=[str(exc)],
                as_json=as_json,
            )
        )
    sys.exit(
        _emit(
            "manifest update",
            ok=True,
            summary={
                "entries": len(loaded.entries),
                "active": len(loaded.active),
                "withdrawn": len(withdrawn),
            },
            items=[],
            errors=[],
            as_json=as_json,
        )
    )


if __name__ == "__main__":
    main()
