"""The ``loremfile`` command line interface (docs/06 §10).

Commands are added by the milestone that implements them. Present so far:

* ``catalog validate`` — M1.6
* ``manifest check`` / ``manifest update`` — M1.6, for the parts that do not need
  generated bytes. Building entries from ``build/fixtures/`` needs the generators and
  validators, so it arrives with M3.

Every command exits non-zero on any failure and supports ``--json``, which prints one
object: ``{"command", "ok", "summary", "items", "errors"}``.
"""

from __future__ import annotations

import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import click

from loremfile import __version__, config, validators
from loremfile import build as build_module
from loremfile.catalog import Catalog, CatalogError
from loremfile.manifest import (
    LOCKED_FIELDS,
    Manifest,
    ManifestError,
    build_entry,
    render_formats_json,
    render_sha256sums,
)

Item = dict[str, str]


def _emit(
    command: str,
    *,
    ok: bool,
    summary: dict[str, Any],
    items: list[Item],
    errors: list[str],
    as_json: bool,
) -> int:
    if as_json:
        click.echo(
            json.dumps(
                {
                    "command": command,
                    "ok": ok,
                    "summary": summary,
                    "items": items,
                    "errors": errors,
                },
                indent=2,
                ensure_ascii=False,
            )
        )
    else:
        for error in errors:
            click.echo(f"error: {error}", err=True)
        parts = ", ".join(f"{key}={value}" for key, value in summary.items())
        click.echo(f"{command}: {'ok' if ok else 'FAILED'}{f' ({parts})' if parts else ''}")
    return 0 if ok else 1


@click.group()
@click.version_option(__version__, "-V", "--version", prog_name="loremfile")
def main() -> None:
    """Generators, validators and tooling for loremfile.dev."""


# --- catalog ---------------------------------------------------------------


@main.group()
def catalog() -> None:
    """Work with catalog/*.yaml."""


@catalog.command("validate")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def catalog_validate(as_json: bool) -> None:
    """Schema and cross-checks on catalog/*.yaml."""
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    try:
        loaded = Catalog.load()
    except (CatalogError, ValueError) as exc:
        errors.append(str(exc))
    else:
        fixtures = list(loaded.fixtures())
        summary = {
            "formats": len(loaded.formats),
            "fixtures": len(fixtures),
            "phase1": sum(1 for f in fixtures if f.phase == 1),
        }
        items = [{"path": f.path, "status": "ok", "detail": f.size_class} for f in fixtures]
    sys.exit(
        _emit(
            "catalog validate",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


# --- build and validate ----------------------------------------------------


def _selection_options(func: Callable[..., None]) -> Callable[..., None]:
    """The filters shared by `build` and `validate` (docs/06 §5)."""
    for option in reversed(
        [
            click.option("--only", multiple=True, metavar="PATH", help="Exact fixture paths."),
            click.option(
                "--format",
                "formats",
                multiple=True,
                metavar="FMT",
                help="Restrict to these formats.",
            ),
            click.option(
                "--group",
                type=click.Choice(["media", "data", "other"]),
                help="Restrict to a format group.",
            ),
            click.option("--phase", type=int, help="Restrict to a catalog phase."),
            click.option("--json", "as_json", is_flag=True, help="Print one JSON object."),
        ]
    ):
        func = option(func)
    return func


@main.command("build")
@click.option(
    "--new",
    "selection",
    flag_value="new",
    help="Only fixtures absent from the merge-base manifest.",
)
@click.option(
    "--missing-in-bucket",
    "selection",
    flag_value="missing-in-bucket",
    help="Only fixtures absent from the bucket (M4.3).",
)
@click.option("--all", "selection", flag_value="all", default=True, help="Every active fixture.")
@_selection_options
def build_command(
    selection: str,
    only: tuple[str, ...],
    formats: tuple[str, ...],
    group: str | None,
    phase: int | None,
    as_json: bool,
) -> None:
    """Generate fixtures into build/fixtures/."""
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        catalog_obj = Catalog.load()
        chosen = build_module.select(
            catalog_obj,
            selection=build_module.Selection(selection),
            only=only,
            formats=formats,
            group=group,
            phase=phase,
        )
        results = build_module.build(chosen)
        build_module.write_receipt(
            chosen,
            selection=selection,
            filters={
                "only": list(only),
                "formats": list(formats),
                "group": group,
                "phase": phase,
            },
        )
        summary = {"generated": len(results), "bytes": sum(len(r.data) for r in results)}
        items = [
            {"path": r.path, "status": "ok", "detail": f"{len(r.data)} bytes"} for r in results
        ]
    except (build_module.BuildError, CatalogError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit("build", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json)
    )


@main.command("validate")
@_selection_options
def validate_command(
    only: tuple[str, ...],
    formats: tuple[str, ...],
    group: str | None,
    phase: int | None,
    as_json: bool,
) -> None:
    """Run the validators over build/fixtures/."""
    errors: list[str] = []
    items: list[Item] = []
    summary: dict[str, Any] = {}
    try:
        catalog_obj = Catalog.load()
        build_module.load_generators()
        validators.load()
        chosen = build_module.select(
            catalog_obj, only=only, formats=formats, group=group, phase=phase
        )
        directory = build_module.fixtures_dir()
        # Validate what the preceding build produced, not everything in the catalog.
        # `build --new` generates only the fixtures a pull request adds, and the bare
        # `loremfile validate` that follows it in ci.yml has to mean "check those".
        # Only paths named explicitly with --only are required to be present; anything
        # else simply was not part of this build.
        explicit = set(only)
        present = [f for f in chosen if (directory / f.path).is_file()]
        for path in sorted(explicit - {f.path for f in present}):
            errors.append(f"{path}: not generated; run `loremfile build --only {path}` first")
            items.append({"path": path, "status": "missing", "detail": ""})

        # The receipt says what the last build set out to generate. Anything it selected
        # that is not on disk is a build that half-failed, whatever its exit code said.
        receipt = build_module.read_receipt()
        expected = (
            {p for p in receipt.selected if p in {f.path for f in chosen}} if receipt else set()
        )
        for path in sorted(expected - {f.path for f in present}):
            errors.append(f"{path}: selected by the last build but never written")
            items.append({"path": path, "status": "missing", "detail": ""})

        if not present and not errors and receipt is None:
            # No receipt means no build ran here. An empty directory with a receipt is a
            # build that correctly selected nothing — the shape of a pull request that
            # changes no catalog entry — and reporting that as a failure would make
            # ci.yml red on every infrastructure-only change.
            errors.append(
                "nothing to validate: build/fixtures is empty. Run `loremfile build` first."
            )
        passed = 0
        for fixture in present:
            target = directory / fixture.path
            report = validators.validate(
                target.read_bytes(), fixture, catalog_obj.mime_for(fixture)
            )
            if report.ok:
                passed += 1
                items.append({"path": fixture.path, "status": "ok", "detail": ""})
            else:
                errors += [f"{fixture.path}: {failure}" for failure in report.failures]
                items.append(
                    {"path": fixture.path, "status": "failed", "detail": "; ".join(report.failures)}
                )
        summary = {
            "validated": passed,
            "failed": len(present) - passed,
            "skipped_not_built": len(chosen) - len(present),
            "selected_by_last_build": len(receipt.selected) if receipt else "no build receipt",
        }
    except (build_module.BuildError, CatalogError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "validate", ok=not errors, summary=summary, items=items, errors=errors, as_json=as_json
        )
    )


# --- manifest --------------------------------------------------------------


@main.group()
def manifest() -> None:
    """Work with manifest.json, sha256sums.txt and formats.json."""


def _check_manifest_against_catalog() -> tuple[Manifest, list[str]]:
    """Rules that need no generated bytes: removals, totals, internal consistency."""
    loaded = Manifest.load()
    errors: list[str] = []
    try:
        catalog_obj = Catalog.load()
    except (CatalogError, ValueError) as exc:
        return loaded, [str(exc)]

    catalog_paths = {f.path for f in catalog_obj.fixtures()}
    removable = {f.path: f.removed for f in catalog_obj.fixtures() if f.removed is not None}
    errors += loaded.check_removals(catalog_paths, removable)
    errors += loaded.check_total_bytes()
    return loaded, errors


def _entries_from_build(
    catalog_obj: Catalog, committed: Manifest
) -> tuple[list[dict[str, Any]], list[str]]:
    """Build manifest entries from whatever is in build/fixtures/.

    Only fixtures that were actually generated are considered, so `manifest update`
    after a partial build adds only what that build produced. Every entry is validated
    first: an entry never reaches the manifest without its props being measured.
    """
    build_module.load_generators()
    validators.load()
    directory = build_module.fixtures_dir()
    entries: list[dict[str, Any]] = []
    errors: list[str] = []
    existing = committed.by_path

    for fixture in catalog_obj.fixtures():
        target = directory / fixture.path
        if not target.is_file():
            continue
        data = target.read_bytes()
        mime = catalog_obj.mime_for(fixture)
        report = validators.validate(data, fixture, mime)
        if not report.ok:
            errors += [f"{fixture.path}: {failure}" for failure in report.failures]
            continue
        entry = build_entry(
            fixture,
            data,
            report.props,
            mime,
            added_in=existing.get(fixture.path, {}).get("added_in", config.CATALOG_VERSION),
        )
        entries.append(entry)

    # The lock rule is the point of the whole exercise: refuse before writing.
    diffs = committed.check_lock({e["path"]: e for e in entries})
    errors += [str(diff) for diff in diffs]
    return entries, errors


@manifest.command("check")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_check(as_json: bool) -> None:
    """Verify the committed manifest, including against whatever the build produced.

    docs/06 §7: for every fixture generated in this run, the committed `sha256`, `bytes`
    and `mime` must equal the regenerated values. That half was deferred to M3 and is
    implemented here, in M3.6 — the first milestone where an author's machine and CI
    actually disagreed, because libx264, libvpx and libopus each dispatch on the CPU
    features they find and no ffmpeg flag reaches that choice.

    When they disagree, docs/11 §5 promises the exact entries to commit rather than a
    pair of truncated hashes, so the author can take CI's answer without guessing.
    """
    loaded, errors = _check_manifest_against_catalog()
    items: list[Item] = []
    corrections: list[dict[str, Any]] = []
    regenerated: list[dict[str, Any]] = []
    if not errors:
        try:
            regenerated, lock_errors = _entries_from_build(Catalog.load(), loaded)
        except (build_module.BuildError, CatalogError, ValueError, KeyError) as exc:
            lock_errors = [str(exc)]
        errors += lock_errors
        committed = loaded.by_path
        for entry in regenerated:
            old = committed.get(entry["path"])
            if old is None:
                continue
            differing = [f for f in LOCKED_FIELDS if old.get(f) != entry.get(f)]
            if differing:
                corrections.append(entry)
                items.append(
                    {"path": entry["path"], "status": "differs", "detail": ",".join(differing)}
                )
        errors += loaded.props_warnings({e["path"]: e for e in regenerated})

    active = loaded.active
    summary = {
        "entries": len(loaded.entries),
        "active": len(active),
        "tombstones": len(loaded.entries) - len(active),
        "total_bytes": sum(e["bytes"] for e in active),
        "regenerated": len(regenerated),
    }
    if corrections and not as_json:
        click.echo(
            "\nThe bytes this machine produced differ from the committed manifest. "
            "Encoder libraries dispatch on CPU features, so an author's machine and CI "
            "can disagree; CI is the authority (docs/06 §4). Commit these entries:\n",
            err=True,
        )
        click.echo(json.dumps(corrections, indent=2, ensure_ascii=False, sort_keys=True))
    sys.exit(
        _emit(
            "manifest check",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


@manifest.command("adopt")
@click.option(
    "--from",
    "source",
    required=True,
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="JSON array of entries, as `manifest check` prints them.",
)
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_adopt(source: Path, as_json: bool) -> None:
    """Take CI's entries for fixtures this machine cannot reproduce (docs/06 §4).

    libx264, libvpx and libopus dispatch on the CPU features they find, so an author's
    machine and CI can produce different bytes for the same fixture and no ffmpeg flag
    reaches that choice. CI is the authority, because CI is what builds the bytes the
    deploy uploads — so its entries have to be committable without hand-editing the
    manifest, which AGENTS.md forbids for good reason.

    The refusal that matters is the last one: a fixture already published on the base
    branch may never change its bytes, whatever any machine now produces. Adopting is
    only ever allowed for paths this branch is adding.
    """
    errors: list[str] = []
    items: list[Item] = []
    adopted: list[dict[str, Any]] = []
    try:
        incoming = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(incoming, list):
            raise ValueError("expected a JSON array of manifest entries")
        loaded = Manifest.load()
        catalog_obj = Catalog.load()
        mime_defaults = {fmt.format: fmt.mime for fmt in catalog_obj.formats}
        known = catalog_obj.by_path
        published = build_module.merge_base_manifest().by_path

        for entry in incoming:
            path = entry.get("path")
            if path not in known:
                errors.append(f"{path}: not in the catalog")
                continue
            missing = [f for f in (*LOCKED_FIELDS, "path", "props") if f not in entry]
            if missing:
                errors.append(f"{path}: entry is missing {missing}")
                continue
            was = published.get(path)
            if was is not None:
                frozen = [f for f in LOCKED_FIELDS if was.get(f) != entry.get(f)]
                if frozen:
                    errors.append(
                        f"{path}: already published on the base branch and {frozen} would "
                        "change. Published bytes are frozen forever (docs/01 REQ-2): "
                        "publish a new path with supersededBy instead."
                    )
                    continue
            adopted.append(entry)
            items.append({"path": path, "status": "adopted", "detail": entry["sha256"][:12]})

        if not errors:
            by_path = loaded.by_path
            changed = any(by_path.get(e["path"]) != e for e in adopted)
            for entry in adopted:
                by_path[entry["path"]] = entry
            loaded.entries = sorted(by_path.values(), key=lambda e: e["path"])
            loaded.touch(changed=changed)
            loaded.save()
            config.sha256sums_path().write_text(
                render_sha256sums(loaded), encoding="utf-8", newline="\n"
            )
            config.formats_json_path().write_text(
                render_formats_json(loaded, mime_defaults), encoding="utf-8", newline="\n"
            )
    except (ManifestError, CatalogError, OSError, ValueError, KeyError) as exc:
        errors.append(str(exc))
    sys.exit(
        _emit(
            "manifest adopt",
            ok=not errors,
            summary={"adopted": len(adopted) if not errors else 0},
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


@manifest.command("update")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_update(as_json: bool) -> None:
    """Rewrite manifest.json, sha256sums.txt and formats.json.

    Never hand-edit those files: run this inside the toolchain container and commit
    exactly what it writes (AGENTS.md).
    """
    loaded, errors = _check_manifest_against_catalog()
    if errors:
        sys.exit(
            _emit("manifest update", ok=False, summary={}, items=[], errors=errors, as_json=as_json)
        )
    try:
        catalog_obj = Catalog.load()
        mime_defaults = {fmt.format: fmt.mime for fmt in catalog_obj.formats}
        added, lock_errors = _entries_from_build(catalog_obj, loaded)
        if lock_errors:
            sys.exit(
                _emit(
                    "manifest update",
                    ok=False,
                    summary={},
                    items=[],
                    errors=lock_errors,
                    as_json=as_json,
                )
            )
        by_path = loaded.by_path
        # docs/06 §7 step 5: generated_at moves only when something actually changed,
        # so an unchanged rebuild produces no diff at all. Comparing the assembled
        # entries — not merely "did we build anything" — is what makes that true.
        changed = any(by_path.get(entry["path"]) != entry for entry in added)
        for entry in added:
            by_path[entry["path"]] = entry
        loaded.entries = sorted(by_path.values(), key=lambda e: e["path"])
        changed = changed or loaded.catalog_version != config.CATALOG_VERSION
        loaded.catalog_version = config.CATALOG_VERSION
        loaded.touch(changed=changed)
        loaded.save()
        config.sha256sums_path().write_text(
            render_sha256sums(loaded), encoding="utf-8", newline="\n"
        )
        config.formats_json_path().write_text(
            render_formats_json(loaded, mime_defaults), encoding="utf-8", newline="\n"
        )
    except (ManifestError, CatalogError, OSError) as exc:
        sys.exit(
            _emit(
                "manifest update",
                ok=False,
                summary={},
                items=[],
                errors=[str(exc)],
                as_json=as_json,
            )
        )
    sys.exit(
        _emit(
            "manifest update",
            ok=True,
            summary={"entries": len(loaded.entries), "active": len(loaded.active)},
            items=[],
            errors=[],
            as_json=as_json,
        )
    )


if __name__ == "__main__":
    main()
