"""The ``loremfile`` command line interface (docs/06 §10).

Commands are added by the milestone that implements them. Present so far:

* ``catalog validate`` — M1.6
* ``manifest check`` / ``manifest update`` — M1.6, for the parts that do not need
  generated bytes. Building entries from ``build/fixtures/`` needs the generators and
  validators, so it arrives with M3.

Every command exits non-zero on any failure and supports ``--json``, which prints one
object: ``{"command", "ok", "summary", "items", "errors"}``.
"""

from __future__ import annotations

import json
import sys
from typing import Any

import click

from loremfile import __version__, config
from loremfile.catalog import Catalog, CatalogError
from loremfile.manifest import (
    Manifest,
    ManifestError,
    render_formats_json,
    render_sha256sums,
)

Item = dict[str, str]


def _emit(
    command: str,
    *,
    ok: bool,
    summary: dict[str, Any],
    items: list[Item],
    errors: list[str],
    as_json: bool,
) -> int:
    if as_json:
        click.echo(
            json.dumps(
                {
                    "command": command,
                    "ok": ok,
                    "summary": summary,
                    "items": items,
                    "errors": errors,
                },
                indent=2,
                ensure_ascii=False,
            )
        )
    else:
        for error in errors:
            click.echo(f"error: {error}", err=True)
        parts = ", ".join(f"{key}={value}" for key, value in summary.items())
        click.echo(f"{command}: {'ok' if ok else 'FAILED'}{f' ({parts})' if parts else ''}")
    return 0 if ok else 1


@click.group()
@click.version_option(__version__, "-V", "--version", prog_name="loremfile")
def main() -> None:
    """Generators, validators and tooling for loremfile.dev."""


# --- catalog ---------------------------------------------------------------


@main.group()
def catalog() -> None:
    """Work with catalog/*.yaml."""


@catalog.command("validate")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def catalog_validate(as_json: bool) -> None:
    """Schema and cross-checks on catalog/*.yaml."""
    errors: list[str] = []
    summary: dict[str, Any] = {}
    items: list[Item] = []
    try:
        loaded = Catalog.load()
    except (CatalogError, ValueError) as exc:
        errors.append(str(exc))
    else:
        fixtures = list(loaded.fixtures())
        summary = {
            "formats": len(loaded.formats),
            "fixtures": len(fixtures),
            "phase1": sum(1 for f in fixtures if f.phase == 1),
        }
        items = [{"path": f.path, "status": "ok", "detail": f.size_class} for f in fixtures]
    sys.exit(
        _emit(
            "catalog validate",
            ok=not errors,
            summary=summary,
            items=items,
            errors=errors,
            as_json=as_json,
        )
    )


# --- manifest --------------------------------------------------------------


@main.group()
def manifest() -> None:
    """Work with manifest.json, sha256sums.txt and formats.json."""


def _check_manifest_against_catalog() -> tuple[Manifest, list[str]]:
    """Rules that need no generated bytes: removals, totals, internal consistency."""
    loaded = Manifest.load()
    errors: list[str] = []
    try:
        catalog_obj = Catalog.load()
    except (CatalogError, ValueError) as exc:
        return loaded, [str(exc)]

    catalog_paths = {f.path for f in catalog_obj.fixtures()}
    removable = {f.path: f.removed for f in catalog_obj.fixtures() if f.removed is not None}
    errors += loaded.check_removals(catalog_paths, removable)
    errors += loaded.check_total_bytes()
    return loaded, errors


@manifest.command("check")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_check(as_json: bool) -> None:
    """Verify the committed manifest without writing anything.

    Regenerated-byte comparison is added in M3, when generators and validators exist;
    the lock and removal rules that need only the committed file run today.
    """
    loaded, errors = _check_manifest_against_catalog()
    active = loaded.active
    summary = {
        "entries": len(loaded.entries),
        "active": len(active),
        "tombstones": len(loaded.entries) - len(active),
        "total_bytes": sum(e["bytes"] for e in active),
    }
    sys.exit(
        _emit(
            "manifest check",
            ok=not errors,
            summary=summary,
            items=[],
            errors=errors,
            as_json=as_json,
        )
    )


@manifest.command("update")
@click.option("--json", "as_json", is_flag=True, help="Print one JSON object.")
def manifest_update(as_json: bool) -> None:
    """Rewrite manifest.json, sha256sums.txt and formats.json.

    Never hand-edit those files: run this inside the toolchain container and commit
    exactly what it writes (AGENTS.md).
    """
    loaded, errors = _check_manifest_against_catalog()
    if errors:
        sys.exit(
            _emit("manifest update", ok=False, summary={}, items=[], errors=errors, as_json=as_json)
        )
    try:
        catalog_obj = Catalog.load()
        mime_defaults = {fmt.format: fmt.mime for fmt in catalog_obj.formats}
        loaded.touch(changed=False)
        loaded.save()
        config.sha256sums_path().write_text(
            render_sha256sums(loaded), encoding="utf-8", newline="\n"
        )
        config.formats_json_path().write_text(
            render_formats_json(loaded, mime_defaults), encoding="utf-8", newline="\n"
        )
    except (ManifestError, CatalogError, OSError) as exc:
        sys.exit(
            _emit(
                "manifest update",
                ok=False,
                summary={},
                items=[],
                errors=[str(exc)],
                as_json=as_json,
            )
        )
    sys.exit(
        _emit(
            "manifest update",
            ok=True,
            summary={"entries": len(loaded.entries), "active": len(loaded.active)},
            items=[],
            errors=[],
            as_json=as_json,
        )
    )


if __name__ == "__main__":
    main()
