"""HLS fixtures: a playlist and its segments (docs/05 §3.3).

`hls/720p-10s/` is the catalog's only nested path, and its six files are six separate
fixtures with six separate URLs, because that is how a player fetches them. Each one is
generated by running the same ffmpeg segmenter and returning the member asked for, so a
segment is reproducible on its own without the playlist having to exist first — which is
what the immutability contract needs when only one of them is ever rebuilt.

ffmpeg's HLS muxer writes the playlist with absolute-looking names taken from the output
path, so the playlist is rewritten here to the relative URIs docs/05 §3.3 requires. It is
also the reason the playlist is read as text rather than trusted: a fixture whose URIs
point at a build directory would be useless the moment it was published.
"""

from __future__ import annotations

import re
from pathlib import Path

from loremfile.generators.base import GeneratorContext, generator
from loremfile.util.ffmpeg import encoder_for, run

#: Segment file names, matching the catalog: seg-000.ts, seg-001.ts, ...
SEGMENT_PATTERN = "seg-%03d.ts"
SEGMENT_RE = re.compile(r"^seg-\d{3}\.ts$")
PLAYLIST_NAME = "index.m3u8"

#: The x264 settings the rest of M3.6 uses, so an HLS segment and a plain .ts fixture
#: are encoded the same way.
X264_ARGS = ("-preset", "medium", "-crf", "23", "-pix_fmt", "yuv420p", "-x264-params", "threads=1")


def _render(
    ctx: GeneratorContext,
    *,
    width: int,
    height: int,
    duration: float,
    fps: int,
    segment_seconds: int,
) -> Path:
    """Run the segmenter once into a directory of its own and return that directory."""
    workdir = ctx.workdir / ctx.path.replace("/", "_")
    workdir.mkdir(parents=True, exist_ok=True)
    for stale in workdir.iterdir():
        stale.unlink()
    run(
        [
            "-f",
            "lavfi",
            "-i",
            f"testsrc2=size={width}x{height}:rate={fps}",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000",
            "-t",
            f"{duration:g}",
            "-c:v",
            encoder_for("h264"),
            *X264_ARGS,
            # The segmenter can only cut on a keyframe, and libx264's default GOP is 250
            # frames — about 8 seconds at 30 fps — so a 10-second source came out as two
            # segments, not five. Forcing a keyframe at every segment boundary is what
            # makes the segment count follow from the arithmetic. Scene-cut detection is
            # off for the same reason: it would place keyframes by picture content.
            "-force_key_frames",
            f"expr:gte(t,n_forced*{segment_seconds})",
            "-sc_threshold",
            "0",
            "-c:a",
            encoder_for("aac"),
            "-b:a",
            "128k",
            "-f",
            "hls",
            "-hls_time",
            str(segment_seconds),
            "-hls_playlist_type",
            "vod",
            "-hls_list_size",
            "0",
            "-hls_flags",
            "temp_file",
            "-hls_segment_filename",
            str(workdir / SEGMENT_PATTERN),
            str(workdir / PLAYLIST_NAME),
        ]
    )
    return workdir


def _relative_playlist(text: str) -> str:
    """Rewrite every segment URI to a bare file name, and check nothing else is a path.

    ffmpeg emits whatever it was given as `-hls_segment_filename`, which here is an
    absolute build path. A published playlist has to name its segments relative to
    itself; anything left containing a slash would be a broken fixture that still parses.
    """
    lines = []
    for line in text.splitlines():
        if line.startswith("#") or not line.strip():
            lines.append(line)
            continue
        name = Path(line.strip()).name
        if not SEGMENT_RE.match(name):
            raise ValueError(f"unexpected segment URI in the playlist: {line!r}")
        lines.append(name)
    return "\n".join(lines) + "\n"


@generator(parallel_safe=False)
def member(
    ctx: GeneratorContext,
    *,
    member: str,
    width: int = 1280,
    height: int = 720,
    duration: float = 10,
    fps: int = 30,
    segment_seconds: int = 2,
) -> bytes:
    """One file of the HLS variant: the playlist, or one segment."""
    workdir = _render(
        ctx,
        width=width,
        height=height,
        duration=duration,
        fps=fps,
        segment_seconds=segment_seconds,
    )
    if member == PLAYLIST_NAME:
        playlist = _relative_playlist((workdir / PLAYLIST_NAME).read_text(encoding="utf-8"))
        if "#EXT-X-ENDLIST" not in playlist:
            raise ValueError("the playlist has no #EXT-X-ENDLIST, so it reads as still live")
        return playlist.encode("utf-8")

    target = workdir / member
    if not target.is_file():
        produced = sorted(p.name for p in workdir.iterdir())
        raise ValueError(f"the segmenter produced no '{member}'; it made {produced}")
    return target.read_bytes()
