"""Validator dispatch and the checks every format shares (docs/06 §6).

A validator's job is to read the generated bytes back with an **independent** reader and
report what it measured. The generator says what it meant to produce; the validator
proves it, and the measured ``props`` are what the manifest publishes.

Per-format validators register themselves here. Everything in this module runs for every
fixture regardless of format:

1. magic bytes for the declared format,
2. the ``expect`` block from the catalog,
3. the size class,
4. the content-policy scan,
5. text hygiene — a text-like fixture must decode strictly with its declared charset.
"""

from __future__ import annotations

import importlib
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from loremfile.catalog import Fixture
from loremfile.config import MAX_FIXTURE_BYTES
from loremfile.util.sizing import size_matches
from loremfile.validators import policy

#: A validator reads the bytes plus the resolved Content-Type and returns the props it
#: measured. The mime is passed in because the charset lives there, and a text
#: validator cannot do its job without it.
ValidatorFunc = Callable[[bytes, Fixture, str], dict[str, Any]]

#: Leading bytes each format must start with (docs/06 §6 step 1).
MAGIC: dict[str, tuple[bytes, ...]] = {
    "pdf": (b"%PDF-",),
    "png": (b"\x89PNG\r\n\x1a\n",),
    "jpg": (b"\xff\xd8\xff",),
    "gif": (b"GIF87a", b"GIF89a"),
    "flac": (b"fLaC",),
    "ogg": (b"OggS",),
    "zip": (b"PK\x03\x04", b"PK\x05\x06"),
    "7z": (b"7z\xbc\xaf\x27\x1c",),
    "gz": (b"\x1f\x8b",),
    "bz2": (b"BZh",),
    "xz": (b"\xfd7zXZ\x00",),
    "zst": (b"\x28\xb5\x2f\xfd",),
    "parquet": (b"PAR1",),
    "sqlite": (b"SQLite format 3\x00",),
    "woff": (b"wOFF",),
    "woff2": (b"wOF2",),
    "ttf": (b"\x00\x01\x00\x00",),
    "otf": (b"OTTO",),
    "wasm": (b"\x00asm",),
}

#: Floats in `expect` are compared to this tolerance (docs/06 §6 step 3).
FLOAT_TOLERANCE = 0.01

#: Charsets a fixture may declare. Anything else is a typo until proven otherwise.
KNOWN_CHARSETS = frozenset(
    {
        "utf-8",
        "utf-16",
        "utf-16le",
        "utf-16be",
        "utf-32",
        "utf-32le",
        "utf-32be",
        "iso-8859-1",
        "windows-1252",
        "shift_jis",
        "gb2312",
        "us-ascii",
    }
)


class ValidationError(Exception):
    """A fixture failed validation. Always fatal: it never reaches the manifest."""


@dataclass
class Report:
    """What a validation run found for one fixture."""

    path: str
    props: dict[str, Any] = field(default_factory=dict)
    failures: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.failures


_REGISTRY: dict[str, ValidatorFunc] = {}

#: Validator modules to import so their @register decorators run. A family is added
#: here by the same pull request that adds its generator — docs/06 §13 requires the two
#: to ship together, and an unregistered validator is how that rule gets broken quietly.
VALIDATOR_MODULES = ("binary", "text", "data", "columnar", "geo")


def load() -> None:
    """Import the per-format validator modules so the registry is populated."""
    for name in VALIDATOR_MODULES:
        importlib.import_module(f"loremfile.validators.{name}")


def register(fmt: str) -> Callable[[ValidatorFunc], ValidatorFunc]:
    """Register the validator for a format."""

    def decorate(func: ValidatorFunc) -> ValidatorFunc:
        if fmt in _REGISTRY:
            raise ValueError(f"a validator for '{fmt}' is already registered")
        _REGISTRY[fmt] = func
        return func

    return decorate


def has_validator(fmt: str) -> bool:
    return fmt in _REGISTRY


def charset_of(mime: str) -> str | None:
    """The charset from a Content-Type, lowercased, or ``None``."""
    for part in mime.split(";")[1:]:
        key, _, value = part.strip().partition("=")
        if key.strip().lower() == "charset":
            return value.strip().strip('"').lower()
    return None


def check_magic(data: bytes, fixture: Fixture) -> list[str]:
    """Magic bytes for the declared format.

    Edge fixtures are exempt: their whole purpose is to be wrong in a declared way, and
    the edge validator asserts the specific defect instead (M3.8).
    """
    if fixture.format == "edge":
        return []
    expected = MAGIC.get(fixture.format)
    if not expected:
        return []
    if any(data.startswith(prefix) for prefix in expected):
        return []
    shown = " or ".join(prefix.hex() for prefix in expected)
    return [f"does not start with {fixture.format} magic ({shown}); got {data[:8].hex()}"]


def check_expectations(props: dict[str, Any], fixture: Fixture) -> list[str]:
    """Every key in the catalog's ``expect`` must equal what was measured."""
    failures = []
    for key, wanted in (fixture.expect or {}).items():
        if key not in props:
            failures.append(f"expect.{key} was not measured by the validator")
            continue
        got = props[key]
        if isinstance(wanted, float) or isinstance(got, float):
            if abs(float(got) - float(wanted)) > FLOAT_TOLERANCE:
                failures.append(f"expect.{key}: wanted {wanted}, measured {got}")
        elif got != wanted:
            failures.append(f"expect.{key}: wanted {wanted!r}, measured {got!r}")
    return failures


def check_size(data: bytes, fixture: Fixture) -> list[str]:
    """The size class the catalog claims, plus the hard per-fixture cap."""
    failures = []
    if len(data) > MAX_FIXTURE_BYTES and not fixture.allow_large:
        failures.append(f"{len(data)} bytes exceeds MAX_FIXTURE_BYTES {MAX_FIXTURE_BYTES}")
    if not size_matches(len(data), fixture.size_class, fixture.nominal_bytes):
        failures.append(
            f"size_class {fixture.size_class} with nominal {fixture.nominal_bytes} "
            f"does not hold for {len(data)} bytes"
        )
    return failures


def check_text_hygiene(data: bytes, fixture: Fixture, mime: str) -> list[str]:
    """A text-like fixture must decode strictly with the charset it declares.

    Edge fixtures whose declared defect is ``invalid-encoding`` are exempt — being
    undecodable is the point of those.
    """
    charset = charset_of(mime)
    if charset is None:
        return []
    if charset not in KNOWN_CHARSETS:
        return [f"declares an unrecognised charset {charset!r}"]
    if fixture.edge is not None and fixture.edge.defect.value == "invalid-encoding":
        return []
    try:
        data.decode(charset, errors="strict")
    except (UnicodeDecodeError, LookupError) as exc:
        return [f"does not decode as {charset}: {exc}"]
    return []


def validate(data: bytes, fixture: Fixture, mime: str) -> Report:
    """Run every check for one fixture and return what was measured."""
    report = Report(path=fixture.path)

    if has_validator(fixture.format):
        try:
            report.props = _REGISTRY[fixture.format](data, fixture, mime)
        except ValidationError as exc:
            report.failures.append(str(exc))
        except Exception as exc:  # a reader blowing up is a validation failure
            report.failures.append(f"{type(exc).__name__} while reading it back: {exc}")
    else:
        report.failures.append(
            f"no validator registered for format '{fixture.format}'; "
            "every generator family ships with its validator in the same pull request"
        )

    report.failures += check_magic(data, fixture)
    report.failures += check_size(data, fixture)
    report.failures += check_text_hygiene(data, fixture, mime)
    report.failures += check_expectations(report.props, fixture)
    report.failures += [
        str(violation)
        for violation in policy.scan(fixture.path, data, exceptions=fixture.policy_exceptions)
    ]
    return report
