"""Content-policy scan over generated bytes (docs/06 §6 step 5, docs/13 §5).

This is the last line of defence before a file is published. It runs on **every**
fixture, whatever its format, because the cost of shipping something dangerous is far
higher than the cost of scanning a few hundred megabytes.

Format-specific checks — the SVG and HTML event-handler rules — arrive with M3.8
alongside `edge.py`; the checks here are the format-agnostic ones that apply from the
first fixture onwards.

Exceptions are declared **by path** in the catalog's ``policy_exceptions`` and the
manifest records the resulting hash, so every exception is auditable.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

#: The EICAR anti-malware test string, split so this source file does not itself trip
#: a scanner. Reassembled at import.
_EICAR = "X5O!P%@AP[4" + "\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
EICAR_BYTES = _EICAR.encode("ascii")

PRIVATE_KEY = re.compile(rb"-----BEGIN [A-Z ]*PRIVATE KEY-----")
EXTERNAL_ENTITY = re.compile(rb"<!ENTITY\s[^>]*\b(SYSTEM|PUBLIC)\b", re.IGNORECASE)

#: Executable magic. A fixture is never an executable (docs/13 §5).
EXECUTABLE_MAGIC: tuple[tuple[bytes, str], ...] = (
    (b"MZ", "mz-prefix"),
    (b"\x7fELF", "elf"),
    (b"\xfe\xed\xfa\xce", "mach-o-32"),
    (b"\xfe\xed\xfa\xcf", "mach-o-64"),
    (b"\xce\xfa\xed\xfe", "mach-o-32-le"),
    (b"\xcf\xfa\xed\xfe", "mach-o-64-le"),
    (b"\xca\xfe\xba\xbe", "mach-o-fat"),
)

#: Ratio above which an archive counts as a decompression bomb.
MAX_DECOMPRESSION_RATIO = 1000


@dataclass(frozen=True)
class PolicyViolation:
    path: str
    rule: str
    detail: str

    def __str__(self) -> str:
        return f"{self.path}: {self.rule} — {self.detail}"


def _exception_names(exceptions: list[str]) -> set[str]:
    """``decompression-ratio:2100`` is declared as one token; match on its name."""
    return {item.split(":", 1)[0] for item in exceptions}


def scan(path: str, data: bytes, *, exceptions: list[str] | None = None) -> list[PolicyViolation]:
    """Check bytes against the format-agnostic content policy.

    Returns every violation rather than the first, so a contributor sees the whole
    problem in one run.
    """
    declared = _exception_names(exceptions or [])
    violations: list[PolicyViolation] = []

    if PRIVATE_KEY.search(data) and "private-key" not in declared:
        violations.append(PolicyViolation(path, "private-key", "contains a PEM private key header"))

    if EICAR_BYTES in data and "eicar" not in declared:
        violations.append(PolicyViolation(path, "eicar", "contains the EICAR test string"))

    for magic, name in EXECUTABLE_MAGIC:
        if data.startswith(magic) and name not in declared:
            violations.append(
                PolicyViolation(path, "executable", f"starts with {name} magic bytes")
            )

    if EXTERNAL_ENTITY.search(data) and "external-entity" not in declared:
        violations.append(
            PolicyViolation(path, "external-entity", "declares an external entity (SYSTEM/PUBLIC)")
        )

    return violations


def check_decompression_ratio(
    path: str, compressed: int, uncompressed: int, *, exceptions: list[str] | None = None
) -> list[PolicyViolation]:
    """Archives above the ratio cap are decompression bombs unless declared.

    A declared exception must state the measured ratio — ``decompression-ratio:2100`` —
    so the number is reviewed rather than waved through.
    """
    if compressed <= 0:
        return []
    ratio = uncompressed / compressed
    if ratio <= MAX_DECOMPRESSION_RATIO:
        return []
    if "decompression-ratio" in _exception_names(exceptions or []):
        return []
    return [
        PolicyViolation(
            path,
            "decompression-ratio",
            f"expands {ratio:.0f}:1, above the {MAX_DECOMPRESSION_RATIO}:1 cap",
        )
    ]
