"""M4.3: the operational trio — gh_issue, ops_log and release.

`release` is the one to read carefully. It assembles the restore archive from the bytes
**production served**, and nothing is published yet, so `fetch` has never been called
against a real object. These tests drive it against a fake: **a green suite here is not
end-to-end verification**, and the first real run is the M5.5 restore drill.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import tarfile
from pathlib import Path
from typing import Any

import pytest

from loremfile import gh_issue, ops_log
from loremfile.infra import release
from loremfile.infra.release import ReleaseError


def entry(path: str, body: bytes) -> dict[str, Any]:
    return {"path": path, "bytes": len(body), "sha256": hashlib.sha256(body).hexdigest()}


# --- release ----------------------------------------------------------------


def test_the_archive_holds_what_production_served_not_a_rebuild(tmp_path: Path) -> None:
    """The whole point: an archive of regenerated bytes proves only that generators run."""
    bodies = {"pdf/a.pdf": b"%PDF-a", "png/b.png": b"\x89PNG-b"}
    entries = [entry(path, body) for path, body in bodies.items()]

    archive = release.build_archive(
        entries, lambda path: bodies[path], tmp_path, stem="fixtures-v1-v2"
    )
    assert archive.members == 2
    with tarfile.open(archive.parts[0]) as tar:
        assert sorted(tar.getnames()) == ["pdf/a.pdf", "png/b.png"]
        assert tar.extractfile("pdf/a.pdf").read() == b"%PDF-a"  # type: ignore[union-attr]


def test_a_member_that_does_not_match_the_manifest_is_refused(tmp_path: Path) -> None:
    """A restore path built from unverified bytes restores whatever it was handed."""
    entries = [entry("pdf/a.pdf", b"%PDF-a")]
    with pytest.raises(ReleaseError, match="not a restore path"):
        release.build_archive(entries, lambda _p: b"%PDF-tampered", tmp_path, stem="fixtures")


def test_a_member_of_the_wrong_length_is_refused(tmp_path: Path) -> None:
    e = entry("pdf/a.pdf", b"%PDF-a")
    e["bytes"] = 999
    with pytest.raises(ReleaseError, match="bytes"):
        release.build_archive([e], lambda _p: b"%PDF-a", tmp_path, stem="fixtures")


def test_archives_split_into_parts_with_a_listing(tmp_path: Path) -> None:
    bodies = {f"bin/{n}.bin": bytes([n]) * 100 for n in range(5)}
    entries = [entry(path, body) for path, body in bodies.items()]
    archive = release.build_archive(
        entries, lambda p: bodies[p], tmp_path, stem="fixtures", part_limit=250
    )
    assert len(archive.parts) > 1
    listing = (tmp_path / "parts.txt").read_text()
    for path in archive.parts:
        assert path.name in listing
        assert archive.digests[path.name] in listing


def test_the_delta_skips_paths_the_previous_release_already_shipped() -> None:
    """A published path cannot change its bytes, so shipping it again only adds size."""
    previous = [entry("pdf/a.pdf", b"a")]
    current = [entry("pdf/a.pdf", b"a"), entry("png/b.png", b"b")]
    assert [e["path"] for e in release.added_since(current, previous)] == ["png/b.png"]


def test_the_archive_is_reproducible_for_the_same_inputs(tmp_path: Path) -> None:
    """Fixed member metadata: the same fixtures make the same archive."""
    bodies = {"pdf/a.pdf": b"%PDF-a"}
    entries = [entry(path, body) for path, body in bodies.items()]
    first = release.build_archive(entries, lambda p: bodies[p], tmp_path / "one", stem="f")
    second = release.build_archive(entries, lambda p: bodies[p], tmp_path / "two", stem="f")
    assert first.digests["f.part1.tar"] == second.digests["f.part1.tar"]


# --- ops_log ----------------------------------------------------------------


def usage_report(class_b: int = 1234, ok: bool = True) -> dict[str, Any]:
    return {
        "command": "usage",
        "ok": ok,
        "summary": {
            "r2_class_a_mtd": 56,
            "r2_class_b_mtd": class_b,
            "missing_key_reads": 1329,
        },
        "errors": [],
    }


def test_the_weekly_row_carries_the_numbers_health_watches(tmp_path: Path) -> None:
    report = tmp_path / "usage.json"
    report.write_text(json.dumps(usage_report()))
    log = tmp_path / "ops-log.md"
    line = ops_log.append(report, log, today=dt.date(2026, 9, 14))
    assert "2026-09-14" in line
    assert "1,234" in line
    assert "1,329" in line
    assert log.read_text().startswith("# ops-log")


def test_running_twice_in_one_day_replaces_rather_than_doubles(tmp_path: Path) -> None:
    """A re-run of the scheduled job must not double-count the week."""
    report = tmp_path / "usage.json"
    log = tmp_path / "ops-log.md"
    report.write_text(json.dumps(usage_report(class_b=1)))
    ops_log.append(report, log, today=dt.date(2026, 9, 14))
    report.write_text(json.dumps(usage_report(class_b=2)))
    ops_log.append(report, log, today=dt.date(2026, 9, 14))

    rows = [line for line in log.read_text().splitlines() if line.startswith("| 2026-09-14")]
    assert len(rows) == 1
    assert "| 2 |" in rows[0]


def test_a_failed_usage_read_is_visible_in_the_row(tmp_path: Path) -> None:
    """A week with no numbers must not look like a week with zero traffic."""
    report = tmp_path / "usage.json"
    report.write_text(json.dumps({"command": "usage", "ok": False, "summary": {}, "errors": ["x"]}))
    line = ops_log.append(report, tmp_path / "ops-log.md", today=dt.date(2026, 9, 14))
    assert "—" in line, "an absent number must not render as 0"
    assert "check failed" in line


# --- gh_issue ---------------------------------------------------------------


def test_a_failing_report_becomes_a_body_with_its_numbers(tmp_path: Path) -> None:
    report = tmp_path / "health.json"
    report.write_text(
        json.dumps(
            {"command": "verify-live", "ok": False, "summary": {"failing": 2}, "errors": ["a", "b"]}
        )
    )
    body = gh_issue.summarise(report)
    assert "verify-live" in body
    assert "| failing | 2 |" in body
    assert "a" in body and "b" in body


def test_a_long_error_list_is_truncated_rather_than_dumped(tmp_path: Path) -> None:
    """A body nobody reads is not a report."""
    report = tmp_path / "health.json"
    report.write_text(
        json.dumps({"ok": False, "summary": {}, "errors": [f"e{n}" for n in range(50)]})
    )
    body = gh_issue.summarise(report)
    assert "and 30 more" in body


def test_green_with_nothing_open_does_nothing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: None)
    outcome = gh_issue.apply(label="health", title="t", report=tmp_path / "x.json", state="ok")
    assert outcome.action == "unchanged"


def test_green_closes_an_open_issue(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """The half that makes the label mean something: a tracker where nothing closes."""
    calls: list[list[str]] = []
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: 7)
    monkeypatch.setattr(gh_issue, "_gh", lambda args, **_k: calls.append(args) or "")
    outcome = gh_issue.apply(label="health", title="t", report=tmp_path / "x.json", state="ok")
    assert outcome.action == "closed"
    assert calls[0][:2] == ["issue", "close"]


def test_a_repeat_failure_comments_rather_than_opening_a_second_issue(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Seven days of failure is one issue with seven comments, not seven issues."""
    report = tmp_path / "health.json"
    report.write_text(json.dumps({"ok": False, "summary": {}, "errors": ["x"]}))
    calls: list[list[str]] = []
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: 7)
    monkeypatch.setattr(gh_issue, "_gh", lambda args, **_k: calls.append(args) or "")
    outcome = gh_issue.apply(label="health", title="t", report=report, state="failing")
    assert outcome.action == "commented"
    assert calls[0][:2] == ["issue", "comment"]
