"""M4.3: the operational trio — gh_issue, ops_log and release.

`release` is the one to read carefully. It assembles the restore archive from the bytes
**production served**, and nothing is published yet, so `fetch` has never been called
against a real object. These tests drive it against a fake: **a green suite here is not
end-to-end verification**, and the first real run is the M5.5 restore drill.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import tarfile
from pathlib import Path
from typing import Any

import pytest

from loremfile import gh_issue, ops_log
from loremfile.infra import release
from loremfile.infra.release import ReleaseError


def entry(path: str, body: bytes) -> dict[str, Any]:
    return {"path": path, "bytes": len(body), "sha256": hashlib.sha256(body).hexdigest()}


# --- release ----------------------------------------------------------------


def test_the_archive_holds_what_production_served_not_a_rebuild(tmp_path: Path) -> None:
    """The whole point: an archive of regenerated bytes proves only that generators run."""
    bodies = {"pdf/a.pdf": b"%PDF-a", "png/b.png": b"\x89PNG-b"}
    entries = [entry(path, body) for path, body in bodies.items()]

    archive = release.build_archive(
        entries, lambda path: bodies[path], tmp_path, stem="fixtures-v1-v2"
    )
    assert archive.members == 2
    with tarfile.open(archive.parts[0]) as tar:
        assert sorted(tar.getnames()) == ["pdf/a.pdf", "png/b.png"]
        assert tar.extractfile("pdf/a.pdf").read() == b"%PDF-a"  # type: ignore[union-attr]


def test_a_member_that_does_not_match_the_manifest_is_refused(tmp_path: Path) -> None:
    """A restore path built from unverified bytes restores whatever it was handed."""
    entries = [entry("pdf/a.pdf", b"%PDF-a")]
    with pytest.raises(ReleaseError, match="not a restore path"):
        release.build_archive(entries, lambda _p: b"%PDF-tampered", tmp_path, stem="fixtures")


def test_a_member_of_the_wrong_length_is_refused(tmp_path: Path) -> None:
    e = entry("pdf/a.pdf", b"%PDF-a")
    e["bytes"] = 999
    with pytest.raises(ReleaseError, match="bytes"):
        release.build_archive([e], lambda _p: b"%PDF-a", tmp_path, stem="fixtures")


def test_archives_split_into_parts_with_a_listing(tmp_path: Path) -> None:
    bodies = {f"bin/{n}.bin": bytes([n]) * 100 for n in range(5)}
    entries = [entry(path, body) for path, body in bodies.items()]
    archive = release.build_archive(
        entries, lambda p: bodies[p], tmp_path, stem="fixtures", part_limit=250
    )
    assert len(archive.parts) > 1
    listing = (tmp_path / "parts.txt").read_text()
    for path in archive.parts:
        assert path.name in listing
        assert archive.digests[path.name] in listing


def test_the_delta_skips_paths_the_previous_release_already_shipped() -> None:
    """A published path cannot change its bytes, so shipping it again only adds size."""
    previous = [entry("pdf/a.pdf", b"a")]
    current = [entry("pdf/a.pdf", b"a"), entry("png/b.png", b"b")]
    assert [e["path"] for e in release.added_since(current, previous)] == ["png/b.png"]


def test_the_archive_is_reproducible_for_the_same_inputs(tmp_path: Path) -> None:
    """Fixed member metadata: the same fixtures make the same archive."""
    bodies = {"pdf/a.pdf": b"%PDF-a"}
    entries = [entry(path, body) for path, body in bodies.items()]
    first = release.build_archive(entries, lambda p: bodies[p], tmp_path / "one", stem="f")
    second = release.build_archive(entries, lambda p: bodies[p], tmp_path / "two", stem="f")
    assert first.digests["f.part1.tar"] == second.digests["f.part1.tar"]


# --- ops_log ----------------------------------------------------------------


def usage_report(
    class_b: int = 1234, ok: bool = True, daily: list[dict[str, Any]] | None = None
) -> dict[str, Any]:
    return {
        "command": "usage",
        "ok": ok,
        "summary": {
            "r2_class_a_mtd": 56,
            "r2_class_b_mtd": class_b,
            "missing_key_reads": 1329,
        },
        "daily": [] if daily is None else daily,
        "errors": [],
    }


def day(date: str, missing: int, class_b: int | None = None) -> dict[str, Any]:
    return {
        "date": date,
        "r2_class_a": 0,
        "r2_class_b": class_b if class_b is not None else missing,
        "missing_key_reads": missing,
    }


def test_the_log_carries_one_row_per_day_oldest_first(tmp_path: Path) -> None:
    """The number is only useful as a series, so the resolution is the day (docs/19 §3.2)."""
    report = tmp_path / "usage.json"
    report.write_text(
        json.dumps(usage_report(daily=[day("2026-09-10", 1404), day("2026-09-08", 382)]))
    )
    log = tmp_path / "ops-log.md"
    ops_log.append(report, log, today=dt.date(2026, 9, 14))

    written = [line for line in log.read_text().splitlines() if line.startswith("| 2026-")]
    assert [line.split("|")[1].strip() for line in written] == ["2026-09-08", "2026-09-10"]
    assert "382" in written[0]
    assert "1,404" in written[1]


def test_overlapping_backfills_converge_on_one_row_per_day(tmp_path: Path) -> None:
    """Weekly commits with a 32-day window overlap by design; they must not double-count."""
    report = tmp_path / "usage.json"
    log = tmp_path / "ops-log.md"
    report.write_text(
        json.dumps(usage_report(daily=[day("2026-09-08", 382), day("2026-09-09", 1)]))
    )
    ops_log.append(report, log, today=dt.date(2026, 9, 14))
    report.write_text(
        json.dumps(usage_report(daily=[day("2026-09-09", 1385), day("2026-09-10", 1404)]))
    )
    ops_log.append(report, log, today=dt.date(2026, 9, 21))

    written = [line for line in log.read_text().splitlines() if line.startswith("| 2026-")]
    assert [line.split("|")[1].strip() for line in written] == [
        "2026-09-08",
        "2026-09-09",
        "2026-09-10",
    ]
    assert "1,385" in written[1], "the later read must replace the earlier one, not sit beside it"


def test_a_log_written_before_the_daily_series_is_not_corrupted(tmp_path: Path) -> None:
    """The `ops-log` branch may already hold weekly rows; a backfill must merge into them."""
    log = tmp_path / "ops-log.md"
    log.write_text(
        "# ops-log\n\n| week | R2 class A | R2 class B | missing-key GETs | notes |\n"
        "|---|---|---|---|---|\n| 2026-09-07 | 56 | 1,234 | 1,329 |  |\n"
    )
    report = tmp_path / "usage.json"
    report.write_text(json.dumps(usage_report(daily=[day("2026-09-08", 382)])))
    ops_log.append(report, log, today=dt.date(2026, 9, 14))

    text = log.read_text()
    assert text.startswith("# ops-log")
    written = [line for line in text.splitlines() if line.startswith("| 2026-")]
    assert [line.split("|")[1].strip() for line in written] == ["2026-09-07", "2026-09-08"]


def test_a_failed_usage_read_is_visible_in_the_row(tmp_path: Path) -> None:
    """A day with no numbers must not look like a day with zero traffic."""
    report = tmp_path / "usage.json"
    report.write_text(json.dumps({"command": "usage", "ok": False, "summary": {}, "errors": ["x"]}))
    line = ops_log.append(report, tmp_path / "ops-log.md", today=dt.date(2026, 9, 14))
    assert "—" in line, "an absent number must not render as 0"
    assert "check failed" in line
    assert "| 0 |" not in line


def test_the_em_dash_is_not_a_coincidence_of_the_failure_path(tmp_path: Path) -> None:
    """Negative control for the row above: a real zero renders as `0`, not as an em dash.

    Without this, a formatter that rendered *every* cell as `—` would pass the test above
    while destroying the series.
    """
    report = tmp_path / "usage.json"
    report.write_text(json.dumps(usage_report(daily=[day("2026-09-08", 0, class_b=0)])))
    line = ops_log.append(report, tmp_path / "ops-log.md", today=dt.date(2026, 9, 14))
    assert "| 0 |" in line
    assert "—" not in line


# --- gh_issue ---------------------------------------------------------------


def test_a_failing_report_becomes_a_body_with_its_numbers(tmp_path: Path) -> None:
    report = tmp_path / "health.json"
    report.write_text(
        json.dumps(
            {"command": "verify-live", "ok": False, "summary": {"failing": 2}, "errors": ["a", "b"]}
        )
    )
    body = gh_issue.summarise(report)
    assert "verify-live" in body
    assert "| failing | 2 |" in body
    assert "a" in body and "b" in body


def test_a_long_error_list_is_truncated_rather_than_dumped(tmp_path: Path) -> None:
    """A body nobody reads is not a report."""
    report = tmp_path / "health.json"
    report.write_text(
        json.dumps({"ok": False, "summary": {}, "errors": [f"e{n}" for n in range(50)]})
    )
    body = gh_issue.summarise(report)
    assert "and 30 more" in body


def test_green_with_nothing_open_does_nothing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: None)
    outcome = gh_issue.apply(label="health", title="t", report=tmp_path / "x.json", state="ok")
    assert outcome.action == "unchanged"


def test_green_closes_an_open_issue(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """The half that makes the label mean something: a tracker where nothing closes."""
    calls: list[list[str]] = []
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: 7)
    monkeypatch.setattr(gh_issue, "_gh", lambda args, **_k: calls.append(args) or "")
    outcome = gh_issue.apply(label="health", title="t", report=tmp_path / "x.json", state="ok")
    assert outcome.action == "closed"
    assert calls[0][:2] == ["issue", "close"]


def test_a_repeat_failure_comments_rather_than_opening_a_second_issue(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Seven days of failure is one issue with seven comments, not seven issues."""
    report = tmp_path / "health.json"
    report.write_text(json.dumps({"ok": False, "summary": {}, "errors": ["x"]}))
    calls: list[list[str]] = []
    monkeypatch.setattr(gh_issue, "find_open", lambda *_a: 7)
    monkeypatch.setattr(gh_issue, "_gh", lambda args, **_k: calls.append(args) or "")
    outcome = gh_issue.apply(label="health", title="t", report=report, state="failing")
    assert outcome.action == "commented"
    assert calls[0][:2] == ["issue", "comment"]
