"""Every containerised step that runs git trusts the checkout first (docs/09 §3.5).

actions/checkout marks the repository safe only in a temporary global git config it creates
for its own step ("Temporarily overriding HOME=… before making global git config changes").
In a job container the checkout belongs to the runner's uid and git runs as root, so a later
git call is refused as "dubious ownership". The first `release.yml` rehearsal (run
34982012684) died on exactly that, in `git tag --merged HEAD`, before downloading anything.
The unit tests could not see it: their scratch repositories belong to the user running them.

`deploy.yml`'s `infra changed` had the same gap and worked by accident: `manifest check`,
three steps earlier, calls `build.merge_base_manifest`, which writes `safe.directory` into
the container's global config as a side effect. This pins the rule, so no step depends on
another step's side effect.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2]
WORKFLOWS = sorted((ROOT / ".github" / "workflows").glob("*.yml"))
TRUST = 'git config --global --add safe.directory "$GITHUB_WORKSPACE"'
DIRECT_GIT = re.compile(r"(^|[\s;&|(])git\s")
INTERPOLATION = re.compile(r"\$\{\{.*?\}\}", re.DOTALL)
COMMENT = re.compile(r"#.*$", re.MULTILINE)
#: Commands that run git inside the package or a script. Kept honest by the tests at the
#: end, which compare it with what `src/` and `tools/` actually do.
GIT_COMMANDS = (
    "loremfile infra changed",  # infra/changed.py
    "loremfile release archive",  # infra/release.py
    "loremfile release redact",  # release.manifest_at, via infra/redact.py
    "loremfile build --new",  # build.merge_base_manifest
    "loremfile manifest check",  # build.merge_base_manifest
    "loremfile manifest update",  # build.merge_base_manifest
    "loremfile manifest adopt",  # build.merge_base_manifest
    "tools/check_lock.sh",  # git merge-base, git diff
)


def script(step: dict[str, Any]) -> str:
    return COMMENT.sub("", INTERPOLATION.sub(" ", str(step.get("run") or "")))


def first_git(run: str) -> int | None:
    """Where git first runs in a script, directly or through a command that runs it.

    The trust line itself is blanked out first: it is `git config`, and counting it would
    make every trusted step look as though it ran git before trusting the checkout.
    """
    scan = run.replace(TRUST, " " * len(TRUST))
    offsets = [match.start() for match in DIRECT_GIT.finditer(scan)]
    offsets += [scan.find(command) for command in GIT_COMMANDS if command in scan]
    return min(offsets) if offsets else None


def untrusted_git_steps(document: dict[str, Any]) -> list[str]:
    """`job: step` for each git-running step in a container job with no trust before it."""
    problems: list[str] = []
    for job_name, job in (document.get("jobs") or {}).items():
        if "container" not in job:
            continue
        trusted = False
        for index, step in enumerate(job.get("steps") or []):
            run = script(step)
            at = first_git(run)
            trust_at = run.find(TRUST)
            if at is not None and not trusted and not (0 <= trust_at < at):
                problems.append(f"{job_name}: {step.get('name') or step.get('id') or index}")
            trusted = trusted or trust_at >= 0
    return problems


def git_steps() -> set[str]:
    found: set[str] = set()
    for path in WORKFLOWS:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
        for job_name, job in (document.get("jobs") or {}).items():
            if "container" not in job:
                continue
            for index, step in enumerate(job.get("steps") or []):
                if first_git(script(step)) is not None:
                    found.add(
                        f"{path.name} {job_name}: {step.get('name') or step.get('id') or index}"
                    )
    return found


# --- the workflows --------------------------------------------------------------------------


def test_the_scan_finds_the_steps_known_to_run_git() -> None:
    """Empty-set control first: "every git step is trusted" holds over no steps at all."""
    found = git_steps()
    for expected in (
        "release.yml release: Assemble and verify the archive from the published bytes",
        "release.yml rehearse: Assemble and verify the archive, publishing nothing",
        "deploy.yml deploy: Check the regenerated bytes against the manifest",
        "deploy.yml deploy: Decide whether infra/ changed since the last successful deploy",
        "health.yml check: Weekly ops-log commit",
        "ci.yml build-and-validate: Generate the fixtures this pull request adds",
        "ci.yml lint-and-test: Dependency lock is consistent",
        "infra.yml redact: Redact",
    ):
        assert expected in found, expected


@pytest.mark.parametrize("workflow", WORKFLOWS, ids=lambda path: path.name)
def test_every_containerised_git_step_trusts_the_checkout_first(workflow: Path) -> None:
    document = yaml.safe_load(workflow.read_text(encoding="utf-8"))
    assert untrusted_git_steps(document) == [], (
        f"{workflow.name}: add `{TRUST}` before these steps (docs/09 §3.5)"
    )


# --- the rule, against workflows made to break it -----------------------------------------


def job(*steps: dict[str, Any], container: bool = True) -> dict[str, Any]:
    body: dict[str, Any] = {"steps": [{"uses": "actions/checkout@x"}, *steps]}
    if container:
        body["container"] = {"image": "toolchain"}
    return {"jobs": {"j": body}}


ARCHIVE = {"name": "archive", "run": "loremfile release archive --rehearsal"}
TRUSTED = {"name": "trust", "run": TRUST}


@pytest.mark.parametrize(
    ("document", "flagged"),
    [
        (job(ARCHIVE), ["j: archive"]),
        (job(TRUSTED, ARCHIVE), []),
        (job(ARCHIVE, TRUSTED), ["j: archive"]),
        (job({"name": "both", "run": f"{TRUST}\ngit fetch origin"}), []),
        (job({"name": "late", "run": f"git fetch origin\n{TRUST}"}), ["j: late"]),
        (
            job({"name": "pwd", "run": 'git config --global --add safe.directory "$(pwd)"'}),
            ["j: pwd"],
        ),
        (job({"name": "prose", "run": "echo done  # git refuses otherwise"}), []),
        (job(ARCHIVE, container=False), []),
    ],
    ids=[
        "no trust",
        "trusted before",
        "trusted after",
        "trusted earlier in the same step",
        "trusted later in the same step",
        "a different directory",
        "git named only in a comment",
        "not a container job",
    ],
)
def test_the_rule_fires_exactly_when_it_should(
    document: dict[str, Any], flagged: list[str]
) -> None:
    """Negative controls: a guard nobody has watched fail proves nothing (AGENTS.md)."""
    assert untrusted_git_steps(document) == flagged


# --- the command list is a claim about the code ------------------------------------------


def test_the_modules_that_run_git_are_the_ones_listed() -> None:
    """A new module that runs git must add its command to GIT_COMMANDS."""
    runners = sorted(
        str(path.relative_to(ROOT))
        for path in (ROOT / "src").rglob("*.py")
        if 'shutil.which("git")' in path.read_text(encoding="utf-8")
    )
    assert runners == [
        "src/loremfile/build.py",
        "src/loremfile/infra/changed.py",
        "src/loremfile/infra/release.py",
    ]
    scripts = sorted(
        path.name
        for path in (ROOT / "tools").glob("*.sh")
        if DIRECT_GIT.search(path.read_text(encoding="utf-8"))
    )
    # smoke.sh runs only `git --version`, which reads no repository.
    assert scripts == ["check_lock.sh", "smoke.sh"]


def cli_commands_using(names: set[str]) -> set[str]:
    """`loremfile <group> <command>` for every CLI function that reaches one of `names`."""
    tree = ast.parse((ROOT / "src" / "loremfile" / "cli.py").read_text(encoding="utf-8"))
    commands: set[str] = set()
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        reached = {
            getattr(call.func, "attr", "") or getattr(getattr(call.func, "value", None), "id", "")
            for call in ast.walk(node)
            if isinstance(call, ast.Call)
        } | {
            name.value.id
            for name in ast.walk(node)
            if isinstance(name, ast.Attribute) and isinstance(name.value, ast.Name)
        }
        if not reached & names:
            continue
        for decorator in node.decorator_list:
            if (
                isinstance(decorator, ast.Call)
                and isinstance(decorator.func, ast.Attribute)
                and decorator.func.attr == "command"
                and isinstance(decorator.func.value, ast.Name)
                and decorator.args
                and isinstance(decorator.args[0], ast.Constant)
            ):
                commands.add(f"loremfile {decorator.func.value.id} {decorator.args[0].value}")
    return commands


def test_every_cli_command_that_reaches_git_is_listed() -> None:
    reaching = cli_commands_using(
        {"merge_base_manifest", "changed_infra", "release_module", "redact_module"}
    )
    assert reaching == {
        "loremfile manifest check",
        "loremfile manifest update",
        "loremfile manifest adopt",
        "loremfile infra changed",
        "loremfile release archive",
        "loremfile release redact",
    }, "empty-set control, and a change here means GIT_COMMANDS needs one too"
    assert reaching <= set(GIT_COMMANDS)
